hash-format = "sha256"

[[files]]
file = "mods/audio-engine-tweaks.pw.toml"
hash = "e198a93413d773ae3c529de4ca3493d0355aec30620efb5a852c8455cff04e17"
metafile = true

[[files]]
file = "mods/auto-gg.pw.toml"
hash = "2c5459f32b0b2d1439c19cbbe55f6f323a40ee0705479818f623b52c0f1edc04"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "745a859bf5bcbc1f86f4f6775e43763fc61c4baa7955ecef2cdd91d4ce6cb0ed"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "ec3d49654066ebea35bc58c60d6fff2d9a6664b522ed99d6547d184e1d720a09"
metafile = true

[[files]]
file = "mods/betternightvision.pw.toml"
hash = "396f85cdfa6a7adb20837522efd40d5ca98386e997865d3e260b8d4c531693ea"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e1207ff71f5a6b65ef08c05e3446cb6e63d3880bf7b5f08171d788167bf5a611"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "958853e7993449248fa19b33fb6ca8dec7b8913d7a21ffbc5db68d32a1ac02fb"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "8129dfedced146e716b8193a7aea28ddcf9e617136ac432e6e413d7df7636f26"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "f9baea616b5d71d7d8dd969e38e6faf10e1331a1c37959f8b44b34669321053e"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "4aa7f93edde1b5af8d6c5070916345ec66e2a6b107b21a4f1ce661b6b1111004"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0ccdc424f79a941e9666fafa82520e7f3946b227c8ea3888e94c026cb7dd4f1a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "98e963bf5542d3bfec0eda3ec7b013b490b100a6098cd197dd24e6b0474179f0"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "294e4f0efa851c45ef7641ee738ffc6f32c173657d65aab50ea7d369214cde57"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "937dc6c975101612988ec2adbc5dbcdddc697ed04d5437e2c7a93eef17372460"
metafile = true

[[files]]
file = "mods/island-utils.pw.toml"
hash = "da64f54e396edb337280e0f703a3c8e4346369b0dfeaf553929795e68c70d52f"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "2fed0f45a2c12d3882e8f40b60536bc802d18763cf32d4a136420082cc3c5c43"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "a60191aea3632a323b53598905c500349564f767d5a919ceca946b81f854c8d4"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "fd9f96cd5121c51e259970447529c58a1e100c51ddb206dddbc42a2e60f1c3f8"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "4ecfa16e0a2e863cae7a578300229daa4f5f0a55255edf1aade4519b87123240"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "71ecf8a59064c7ea48bbe727f6b3244d0ab603223c35144e86908f67c5de087c"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "058bb224cee05e304d4472817bb59edff3df1dea4ceb7ece397d03aef421f61f"
metafile = true

[[files]]
file = "mods/simple-block-overlay.pw.toml"
hash = "a3c76b643fd969729097be405c0d311abeda59b49c2d5ab0872ef8021fa6cdf7"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "329eb8b7158d0af310295609b19d80d23e35fed44e9e321ea68131ac7b2efd7a"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "b03140a13089116d045c522b7196af9e72779a3952ce1b277f26a05540565a8c"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2bb9890a188d79e41b30766f670d0de0109e7481bc513dbfdbef088269400016"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "582dd5cb00f2bfb46dfdd9db52d74a50f06676edc2829ff2c87bab5504b76605"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "7b29e50e5eaee20d6cdc59e1cd424945519d75b7c69dd67b3eeb59a31d8a2f33"
metafile = true

[[files]]
file = "mods/toggle-toggle-sprint.pw.toml"
hash = "7ac70dab23c1380e571edde0ac53ee9bf4560a80011e8f657db899ee987d2eaa"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "56f8f259d696e2d370ea3ad21b4db02bb3c8a8bcdeb04a27861fb1550f033748"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "78693c9df5f7591969c42a2ffb6af3a0ecafe7c338ea3ecbf866a55994c0abc4"
metafile = true
