name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9d79c468f6d458cc854d49e09339f9522a9abbbe8663960896a1cf24a3e1dd5"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
