name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce11cc3fae3d671de626589b52667714e8b929ca17cbd476150a26b227b1bd83"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
