name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9eef38f7a42a89227d963a80a9435809d62154796134c04a88702fe639aa1515"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
