name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e42bbb504bdf7aa308802f6b23156f6396b05433f68dbb9daebfc86d12dcda7"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
