hash-format = "sha256"

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "b66693c594e6dc448df36526c9e1785935b89ec154080eea50065077ec2f06c3"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "8493998641d1859c63f6e1a7e4ac3d3f8ec06589d4a18fe6b2fc35fcba89293f"
metafile = true

[[files]]
file = "mods/better-mipmaps.pw.toml"
hash = "d838cde900feba635f9f83c18f9c4c652f275b684d659191654903484e5d07ec"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "bf89455138213232f53816b0c8b620faedf49091c7eddaf8b144c62cf246b089"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e1207ff71f5a6b65ef08c05e3446cb6e63d3880bf7b5f08171d788167bf5a611"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "07077339c5ba5143683354801d8ca7f8f5e4aa764c338eae844de7110e792328"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "2fe800e54f0d8754dafca8affecb63f59cd1e71a9eaf6f0269362d7a9b6a3f43"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "320a29b3b6e11481123565409c0431bb4a0048f8f80d2ad3224d397460b4d707"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0ccdc424f79a941e9666fafa82520e7f3946b227c8ea3888e94c026cb7dd4f1a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "98e963bf5542d3bfec0eda3ec7b013b490b100a6098cd197dd24e6b0474179f0"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "5af11eb601293f738ecd711a27a892287759c93cc9394e4258915fe4839dac25"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "e5628167bee48d16b5a0a383f515ae2fb45fa282eff7d839e4ab8cdaee31f2cc"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "e3bfa3647244df104504a50c8a4e61844312eb8025225af2f24193dfcf7b73b1"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "e0a5061283c7084745ec0594b235ff33b1fd199af023a2dd6ba56f5d2fd26ee9"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "561c21d86927744a430d8fc6ceb3eccc85ae2942f7ad86819d9dac08a4b0fd69"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "65ba2277e82ad58b294517fd99d4f143e69c88cef9dc1b4ad0ce1dcb7cb570f5"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4db7bb421a65d844d19005cfe4035ce8e8caabb17d618dc681ad0ef02665fc78"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "84990c4dfe4273606355b57dccaf599110d1d55a26ca3bdf2904bc8da924ec66"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "cda7bb4e205cef2c1bd8d6f6e35e34a602a0a2d0231b15101385ca720cb67118"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "5123c885d857f0cf319d01e3a9c6451472585ff0062bfee40e16b7f4b3306e45"
metafile = true

[[files]]
file = "mods/lazy-language-loader.pw.toml"
hash = "07632c551f1f3108842ed7dcd0e9d1b1ef19007764057313e2f336744cb68a65"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7addc0aa43dcf34118fe264a9739207dfa768456ba81f065ef396972686469df"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "be18b232a372d09a6acabd762e86ec2fcef8cfbe7633ce7db3a711cf17caea68"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "a60191aea3632a323b53598905c500349564f767d5a919ceca946b81f854c8d4"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "8db428fc8efa8bf1d124b6d2d3ab5e4302efeeff17e73f5e48dd17f4309905e1"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "9e2e0ab14b13ac62d08e4cb122afc21893fa22cd519ad4ebce1da6098d2a99e6"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "e140eb9011500911e5e38cf99a0750f336e164da878ce17e8ccda8f0cb035c88"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "5c8319a0a682557da6c586ff97a31c4b0bd7ca04e01866c4fe7bf5d5aa1c998c"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "a2ed891078c6cb6d90b589022a998b853000af6dcba655ad21932d476567ded8"
metafile = true

[[files]]
file = "mods/sciophobia.pw.toml"
hash = "3104fb523cfd75ff476d39177d12a8d6d19e00ee591484772dac4be000af33b7"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "5a113012ddf7470cc7897d5828a6dc398a6b17f4464169274f606a6d6390fb4a"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "2e640caab93d933838d39580835cd97caf73e8ebc1c2701461701c43128f60ab"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "085d9ed3b61c280978dca7bace2f30c9a45ff4f0a1300939ffff05c0a3a0d426"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "56f8f259d696e2d370ea3ad21b4db02bb3c8a8bcdeb04a27861fb1550f033748"
metafile = true
