name = "OneClient 1.21.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.1-fabric"
update-url = "oneclient/generated/performance-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3993caaa58ff78095a901eac6fd62d76bfbe19d091968231cc5ddf4cf3f20a9"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
