name = "OneClient 1.21.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.1-fabric"
update-url = "oneclient/generated/performance-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f997bf4dcbd23788d14ca86f5a07ebb6ef3d973b309b4dee3a733a1eb9a84878"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
