hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "b00b73591a925431797722b205c9ef7c2ccab8a8592d17fafe6ce0b32f516c06"
metafile = true

[[files]]
file = "mods/anti-dream-skin.pw.toml"
hash = "3b9be8159d079dd74ef7bec98b8dd22507e0a1521840aa138b54d7ad8be45733"
metafile = true

[[files]]
file = "mods/autotip.pw.toml"
hash = "91c58284f949906d92acda34b2476317f1705d78b72c4ffba31526a7408e6121"
metafile = true

[[files]]
file = "mods/blur.pw.toml"
hash = "0ef5717b56e53577c2718d0e356763ed0b63f9b5ea19b4f84dc4be65d5dde775"
metafile = true

[[files]]
file = "mods/colorsaturation.pw.toml"
hash = "7d12c1bf424a0704ca65c3dd14c4b93974824ae96bfb67fb4d6b9aef92e17998"
metafile = true

[[files]]
file = "mods/hytils.pw.toml"
hash = "7200dee3e1983fc57da710142ed37b75b6c4aaf12a6a62fa6dbebe44c36b20b1"
metafile = true

[[files]]
file = "mods/item-physic-lite.pw.toml"
hash = "8d9d02c5d69f87fdac700a64f5350284f23a7caa7031766904571d883cd1115b"
metafile = true

[[files]]
file = "mods/level-head.pw.toml"
hash = "608d0a7375644ed9eb5da1394048b957a464aabf3f8313d1c8f90fc82cb77a54"
metafile = true

[[files]]
file = "mods/mixmetica.pw.toml"
hash = "2e3d572cce1e9bc6de563c50b087e738f3bffbf6c2b1f7e4a18d340fd70cf54e"
metafile = true

[[files]]
file = "mods/oofmod.pw.toml"
hash = "0703d2dd9b33b098f8bd350fdd7c6e64cd820d8a687bdaf9796b86374f90d2e1"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "7a3561100a1c88678a71fe0ab8a106c975273ead0087a1aec65049edafbb2e06"
metafile = true

[[files]]
file = "mods/polyblur.pw.toml"
hash = "f2aefea1eb85362a7e5e914e0c3c4962618d3dc0fe4c9b8bc3b555f38bc206fe"
metafile = true

[[files]]
file = "mods/polynametag.pw.toml"
hash = "0f302f8b44bda8387682bba15203db77a39a3f1afbd2b2c2a89598ecdc1f0007"
metafile = true

[[files]]
file = "mods/polytime.pw.toml"
hash = "8fd44f0c446ee885615927039fadebdebcd6876c037710059038741966031611"
metafile = true

[[files]]
file = "mods/polyweather.pw.toml"
hash = "37a4a568b7dbe306ef07c6ad015eb586493ab954742fa704879d1d35224cde15"
metafile = true

[[files]]
file = "mods/popup-events.pw.toml"
hash = "7edd856e8acbefb848423826ba93cde5c393efd69cc80e70a34d6f9ade03b5ae"
metafile = true

[[files]]
file = "mods/reward-claim.pw.toml"
hash = "d59d1a41956de1d7f1cfb07eedddbbc41d2c2d28bb44007bcb8c8a4e7dd3d90e"
metafile = true

[[files]]
file = "mods/smooth-scrolling-everywhere.pw.toml"
hash = "8cef8a61fc75e87cd99b7f61b87a56b045e69ff66a46c7ff352b8f55ca7af1e9"
metafile = true

[[files]]
file = "mods/tnttime-oneconfig.pw.toml"
hash = "55be4b440b1305c2f75d4686e7b485dc0979700577bafb50a840ef4d296a10b9"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "517b1abf58217b9fbd4d3fc4184274650b7ba5f0f3159610fd6d3734713958dd"
metafile = true
