hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "d707c79d8e6a0a5db930def85eeb272b9f962beaa8e6df0a9168e6c3e8e6520a"
metafile = true

[[files]]
file = "mods/anti-dream-skin.pw.toml"
hash = "83767a0a3408b97552ef465bef64897a1d131b24a558e4c07e1548682eef1b32"
metafile = true

[[files]]
file = "mods/autotip.pw.toml"
hash = "90916762a3972c57872914c2823d8bf828ad921406df221895ce3d089f63df44"
metafile = true

[[files]]
file = "mods/blur.pw.toml"
hash = "4e98c9ab75860b43473b4c1d756bfbe6bc20aae838855641fdd4f15f89f754f8"
metafile = true

[[files]]
file = "mods/colorsaturation.pw.toml"
hash = "7d12c1bf424a0704ca65c3dd14c4b93974824ae96bfb67fb4d6b9aef92e17998"
metafile = true

[[files]]
file = "mods/hytils.pw.toml"
hash = "7200dee3e1983fc57da710142ed37b75b6c4aaf12a6a62fa6dbebe44c36b20b1"
metafile = true

[[files]]
file = "mods/item-physic-lite.pw.toml"
hash = "269c13c475250243b7394d3d2abf9dd4ea8adae1ea68aedfe813cd6e0bfd67a3"
metafile = true

[[files]]
file = "mods/level-head.pw.toml"
hash = "adf0bba3758385e0d2a1ede06bebab1bb865f208be687c722d7baf120440766a"
metafile = true

[[files]]
file = "mods/mixmetica.pw.toml"
hash = "2e3d572cce1e9bc6de563c50b087e738f3bffbf6c2b1f7e4a18d340fd70cf54e"
metafile = true

[[files]]
file = "mods/oofmod.pw.toml"
hash = "0703d2dd9b33b098f8bd350fdd7c6e64cd820d8a687bdaf9796b86374f90d2e1"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "7a3561100a1c88678a71fe0ab8a106c975273ead0087a1aec65049edafbb2e06"
metafile = true

[[files]]
file = "mods/polyblur.pw.toml"
hash = "f2aefea1eb85362a7e5e914e0c3c4962618d3dc0fe4c9b8bc3b555f38bc206fe"
metafile = true

[[files]]
file = "mods/polynametag.pw.toml"
hash = "0f302f8b44bda8387682bba15203db77a39a3f1afbd2b2c2a89598ecdc1f0007"
metafile = true

[[files]]
file = "mods/polytime.pw.toml"
hash = "8fd44f0c446ee885615927039fadebdebcd6876c037710059038741966031611"
metafile = true

[[files]]
file = "mods/polyweather.pw.toml"
hash = "37a4a568b7dbe306ef07c6ad015eb586493ab954742fa704879d1d35224cde15"
metafile = true

[[files]]
file = "mods/popup-events.pw.toml"
hash = "100b3db252f4c93433c94c8a405cba6fc0ee2e39c8267b270bc51c419c929ce0"
metafile = true

[[files]]
file = "mods/redaction.pw.toml"
hash = "fec917e3456da40974fa77636d9dda66b2f0af3e2af631d9bcbefe1f749e95d7"
metafile = true

[[files]]
file = "mods/reward-claim.pw.toml"
hash = "9e198d30a415125dc8b8106cd2bb562888ede75392250f5d602469b8bbcd3b6f"
metafile = true

[[files]]
file = "mods/smooth-scrolling-everywhere.pw.toml"
hash = "9db06e01c71a0f820d8297825cd63342a5f8453ec4b4c7e80930f41a6956756e"
metafile = true

[[files]]
file = "mods/tnt-time.pw.toml"
hash = "f7bd385c32aa8f83ed953c4819b4b0d91f8c4caa60f02aa0e427694882dbb3ec"
metafile = true

[[files]]
file = "mods/tnttime-oneconfig.pw.toml"
hash = "03c6bf779335d66c7b0d2f64e728cfafade2bdc5e91cff3f4fa21cc724506118"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "12dcc564d7e9a7667a6556711667c320fc2edd53dbef65ee7a6c3f22b7b3acf9"
metafile = true
