hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "ac58fb812b76df35e8a05b8bf2f831e3c65ce686d7fa66d25b5c3ff1fb046055"
metafile = true

[[files]]
file = "mods/anti-dream-skin.pw.toml"
hash = "3b9be8159d079dd74ef7bec98b8dd22507e0a1521840aa138b54d7ad8be45733"
metafile = true

[[files]]
file = "mods/autotip.pw.toml"
hash = "91c58284f949906d92acda34b2476317f1705d78b72c4ffba31526a7408e6121"
metafile = true

[[files]]
file = "mods/blur.pw.toml"
hash = "a652b7d881829e752149164f1f8da2c731ba6f8c6232f0e1270693e6a343691b"
metafile = true

[[files]]
file = "mods/colorsaturation.pw.toml"
hash = "368559425b5ee5e5b47b8eef3e2ef4ef5e5ae82fe1e3d3a6e2ff7edeae60090c"
metafile = true

[[files]]
file = "mods/hytils.pw.toml"
hash = "29b168cb73ffe05679c40ac4c52bb876d99155ef8f214141610dfb0a6632a147"
metafile = true

[[files]]
file = "mods/item-physic-lite.pw.toml"
hash = "10c228b7c735dfffcbd21f25f1bf5a5dfe1b828bf2ad303d1ed614a44f7a6f45"
metafile = true

[[files]]
file = "mods/level-head.pw.toml"
hash = "608d0a7375644ed9eb5da1394048b957a464aabf3f8313d1c8f90fc82cb77a54"
metafile = true

[[files]]
file = "mods/mixmetica.pw.toml"
hash = "bb15e8d7603cd57a4525ad5cfda2a6cd620c00e15bbd4391e651dbf5603fb059"
metafile = true

[[files]]
file = "mods/oofmod.pw.toml"
hash = "ca1f42357b1c2f981d67d0b62a5b1874bf5ca4c10c9adfe9a98d7b29fec95e1e"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "9aed01829e028fb8c621e04194f2c871a881c17ebd802cd687b8492f911fa14e"
metafile = true

[[files]]
file = "mods/polyblur.pw.toml"
hash = "a002eaeff2927a06f0b4ce27f5da69f6f9f6bc6c5ba26bf19531be651e09127a"
metafile = true

[[files]]
file = "mods/polynametag.pw.toml"
hash = "079b886b78448b19cad941332b42e949408b9d247c3ba0ae5645f65c13c1f77b"
metafile = true

[[files]]
file = "mods/polytime.pw.toml"
hash = "b283f210eb8a5de715b838538c09edaac1c06143651e4e705cbcadf4655dc60b"
metafile = true

[[files]]
file = "mods/polyweather.pw.toml"
hash = "61ed1daa849edfa93ecab3d7b94ab688ae78d34ce33b91157b74bbcd480e0518"
metafile = true

[[files]]
file = "mods/popup-events.pw.toml"
hash = "7edd856e8acbefb848423826ba93cde5c393efd69cc80e70a34d6f9ade03b5ae"
metafile = true

[[files]]
file = "mods/redaction.pw.toml"
hash = "7721f4b939855fbf3887ffa294cb0c0e88d20d7db5b65aff45c858da48b5cb5f"
metafile = true

[[files]]
file = "mods/reward-claim.pw.toml"
hash = "ecc6dfa3926055fa6ffb883f56300f11e8fafb142bc4b2e3fb2e9588ce85ec98"
metafile = true

[[files]]
file = "mods/smooth-scrolling-everywhere.pw.toml"
hash = "783d9f11968b01ee396fa7c9ece5f4b22b0e02e9f8e1b5fc9d126a6dc72bccf0"
metafile = true

[[files]]
file = "mods/tnttime-oneconfig.pw.toml"
hash = "cd0c8e6643a2e22d715de102ac390ddee714d46e1362f0b7955ff6638e7a50a2"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "64558166eab590db44f51f356cb0540f716d3748da82a3973fe232d09bdba141"
metafile = true
