name = "OneClient 1.8.9 Forge [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.8.9-forge"
update-url = "oneclient/generated/qol-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0ab3fc2360e71fc2fa875f67a0c372f1b9ae75dbc57c1301ef0d1fad5849b42"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
