name = "OneClient 1.8.9 Forge [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.8.9-forge"
update-url = "oneclient/generated/qol-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "587e3dafc7b9951bb95a1f105059883c9f22a17c2b7541c0bfff639d72c5c4b9"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
