name = "OneClient 1.8.9 Forge [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.8.9-forge"
update-url = "oneclient/generated/qol-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d95183ed619334eee9b0a8c5d542a5e4ec0a59420acd73cdab92103a9246b6bc"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
