name = "OneClient 1.8.9 Forge [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.8.9-forge"
update-url = "oneclient/generated/qol-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd27907cf3613cf4b073a22941db0e08e59f230d24dbe9f4946b4537ec697164"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
