hash-format = "sha256"

[[files]]
file = "mods/effecttimerplus.pw.toml"
hash = "8163c65d07e9ae35c9478b84a585718b55db37aedbd88f796efc5082cb0069d4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "208c801e334a46912969bb47b0e21cc503e8a8fc75aa7d0aea85b9d32d7207ae"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "fe249e18bd8e54b678b98df52895a78f51d82f2cef7dc733d9dfbdafb58d81f5"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "31658e52e488c32750f64ea36e34840a671af0f942e7485cb33595b357ca291c"
metafile = true

[[files]]
file = "mods/no-ones-view-model.pw.toml"
hash = "895cef1fb4f90823f35a602104be3edd6b8dadb03117026743bccb377823f353"
metafile = true

[[files]]
file = "mods/shaketweaks.pw.toml"
hash = "77e6bd39928da006c262b78f3f3e49426b56e665dc1f023dd68c135f1b826e22"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "cf4182e58a0917365d20cdcf18c15e32fac5f19445212aeace5cf150b06b1cfb"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1eb89ac2f78826052a7096368ee166836356939e1a139788c2d828f0b44a8371"
metafile = true
