hash-format = "sha256"

[[files]]
file = "mods/effecttimerplus.pw.toml"
hash = "8476aba217c53cf8dc84279531933117cbf5f6fb742e39326b7966a2e44e9b41"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "436fece36e8837e8922762b74763f5600d0190d36c5f7974b02cc06a78a95c7b"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "b65b478c533100542f592cd53d5ed60833dd949f9063de4179aaa7ce50f4cf38"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "a9e2dd8c0765780684783ed4413bba1ffbbf757a431323d1d0b7480329f1fb98"
metafile = true

[[files]]
file = "mods/no-ones-view-model.pw.toml"
hash = "08538b96f42202b783daa4e88b46cfab90b40baaa774f76eb2512cd2ded11f62"
metafile = true

[[files]]
file = "mods/shaketweaks.pw.toml"
hash = "e1c97539e5aea4f508c39b89567ebf737601ba2afa48c998af2b619e8dded9e3"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "29a8eba169cbaa479575f66a05ed864b993df7049133d0463b094313377d6e6d"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "99aa97ac2385770b55de77865426e69e8344d92cfa12ce1abeab8719189350ef"
metafile = true
