name = "OneClient 1.21.8 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.8-fabric"
update-url = "oneclient/generated/pvp-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "452f9c969dd15832ef3b8e14dfc82b366a2f4e21ef419debd50fda654edb063d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
