hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "67e1d61aa9821c8c40c3655d8d3015f34f419705d7fb02c248d04cc5d25f4b9d"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "7b459feedff6d51df5654c789e4241092db8d88716aaa639dd2a29e6a63206a5"
metafile = true

[[files]]
file = "mods/chat-impressive-animation.pw.toml"
hash = "15c07f20f309ac62efc26f6dda97ea06fb58a2e08534c61a0ffdabe9f6c04c9a"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "a3be3c600efd87249fd0640a70e18b4338ef20a1677d8d643e1962ee92efd5cb"
metafile = true

[[files]]
file = "mods/clean-f3.pw.toml"
hash = "4bf830a20e4eab18f0f88dde1e3c84b834103f34975d7d4f385d8302c070a453"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "7e1a4b2596c5d9b228726e1915033197d478b9d23d3a102d0acc4913d843172d"
metafile = true

[[files]]
file = "mods/detail-armor-bar-reconstructed.pw.toml"
hash = "1f821fff3d92359ff7655c65d3959107d0a7ac6c1ae0b8ad3fbfd7b17a70eb54"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "208c801e334a46912969bb47b0e21cc503e8a8fc75aa7d0aea85b9d32d7207ae"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "29eb3d1ac7caa0948596639465a339b37fed1f288c65eb7ede90dce336e6e0ec"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "fe249e18bd8e54b678b98df52895a78f51d82f2cef7dc733d9dfbdafb58d81f5"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "31658e52e488c32750f64ea36e34840a671af0f942e7485cb33595b357ca291c"
metafile = true

[[files]]
file = "mods/tiptapshow.pw.toml"
hash = "2f1a19b23f37e2e3971125a3e8527849f59a31e7edb8ca6bd64c4926c0672832"
metafile = true

[[files]]
file = "mods/ukulib.pw.toml"
hash = "5d4844722727b87c663ca5b26d8a7b4d9a35e97940cb66a66324136b10cdf5ba"
metafile = true

[[files]]
file = "mods/ukus-armor-hud.pw.toml"
hash = "60506af8a4315485c3f3377fa8e6ab2eb26dc4d8ab19758345d2e3fc6f4275b0"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1eb89ac2f78826052a7096368ee166836356939e1a139788c2d828f0b44a8371"
metafile = true
