name = "OneClient 1.21.8 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.8-fabric"
update-url = "oneclient/generated/hud-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "992d6487516259ba723d0537e2a7c342f4cb6574914ab731e125a7e6378a5892"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
