name = "OneClient 1.21.8 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.8-fabric"
update-url = "oneclient/generated/hud-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba91c6e40aed6fcfb0dfc0384025817b8a7817009f3595ae767c5628bcc152bd"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
