name = "OneClient 1.21.8 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.8-fabric"
update-url = "oneclient/generated/hud-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dd552164f3fd1b7cf1af8600f1ca96d8f72dfd2dd78985ade99393aea1fe2fd"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
