name = "OneClient 1.21.8 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.8-fabric"
update-url = "oneclient/generated/hud-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4eb3bef9bef9216299b72bc1ceef9be6269bcdd6205201a95e69d9f3251aab2f"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
