name = "OneClient 1.21.8 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.21.8-fabric"
update-url = "oneclient/generated/hud-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d05710ac7e19bf8c00ec448d7d4f96bd64308c5b3477175c86ec7f2c6ecc0191"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"
