hash-format = "sha256"

[[files]]
file = "mods/arrowpath.pw.toml"
hash = "0f5859934274575fe5143daf5fd278cfc15f604e245e44c6fb769cece64e8a6c"
metafile = true

[[files]]
file = "mods/behindyou.pw.toml"
hash = "86fd754d486efd921190ad3b26acec5f92b2b13758eb38e2c94c8fe2850e11c9"
metafile = true

[[files]]
file = "mods/crosshair.pw.toml"
hash = "c56bb928c7ef40771dadd7d0cb08aee6a3c5fcbc66a188389bd652ca17df373b"
metafile = true

[[files]]
file = "mods/damagetilt.pw.toml"
hash = "88b3a5c628dba4af8c8ea0372fcf54c4ca90362636fe258ee2270cfe3fcccc6d"
metafile = true

[[files]]
file = "mods/damagetint.pw.toml"
hash = "d9dbc9c25663d4b55403f83b71fd99cb72dc2e2cff6cf8df07299c8cc54157a9"
metafile = true

[[files]]
file = "mods/forge-betterhurtcam.pw.toml"
hash = "3e92e6c3f1deabdd098ee22f3e493a7229999eb2d46ee2461c5942ea1971cf8a"
metafile = true

[[files]]
file = "mods/glintcolorizer.pw.toml"
hash = "fd4f7f8f4d38eaaf30e5970dc76f9523cfcfd24cb69073534d9aa89941421cd9"
metafile = true
