hash-format = "sha256"

[[files]]
file = "mods/arrowpath.pw.toml"
hash = "63afd4b32ce04d6d677f7d2f58b893a5fcb04f5ec2336670b573fba44b6d6723"
metafile = true

[[files]]
file = "mods/behindyou.pw.toml"
hash = "86fd754d486efd921190ad3b26acec5f92b2b13758eb38e2c94c8fe2850e11c9"
metafile = true

[[files]]
file = "mods/crosshair.pw.toml"
hash = "c56bb928c7ef40771dadd7d0cb08aee6a3c5fcbc66a188389bd652ca17df373b"
metafile = true

[[files]]
file = "mods/damagetilt.pw.toml"
hash = "776e919404a9d989a626566c5728f1273995b5e81370727e9e7b30253ffe023d"
metafile = true

[[files]]
file = "mods/damagetint.pw.toml"
hash = "d9dbc9c25663d4b55403f83b71fd99cb72dc2e2cff6cf8df07299c8cc54157a9"
metafile = true

[[files]]
file = "mods/forge-betterhurtcam.pw.toml"
hash = "3e92e6c3f1deabdd098ee22f3e493a7229999eb2d46ee2461c5942ea1971cf8a"
metafile = true

[[files]]
file = "mods/glintcolorizer.pw.toml"
hash = "fd4f7f8f4d38eaaf30e5970dc76f9523cfcfd24cb69073534d9aa89941421cd9"
metafile = true
