hash-format = "sha256"

[[files]]
file = "mods/arrowpath.pw.toml"
hash = "288499534199bc042cd55b2a9552782c948401e381f5b0907bb5a89d9163ea48"
metafile = true

[[files]]
file = "mods/behindyou.pw.toml"
hash = "9843c63e8d2ade1518ac7509ef25b24a9ab969f86a0202aad9637afc034c7d7d"
metafile = true

[[files]]
file = "mods/crosshair.pw.toml"
hash = "5bed7abde5edeaead0c0e3557b56301a0c5ef979e46d7e0dc8e94d37ccb765a3"
metafile = true

[[files]]
file = "mods/damagetilt.pw.toml"
hash = "85c082b5f86c3d3490957e938fc506192f4d513460de9c633623744a7b9d22ba"
metafile = true

[[files]]
file = "mods/damagetint.pw.toml"
hash = "d42dd0a0085c2e10836dca4ef2fa2cb9cc07fed3faf698b8a8eff22b708d4ea0"
metafile = true

[[files]]
file = "mods/forge-betterhurtcam.pw.toml"
hash = "fb24e7e6756873844e03d04bf5788e22be02616b551c14a04bfedd26f657830f"
metafile = true

[[files]]
file = "mods/glintcolorizer.pw.toml"
hash = "c6e33dd0d5ab47dc6ae2c0ff344fb7e014b90abe779b713493e6eff124602a2b"
metafile = true
