name = "OneClient 1.8.9 Forge [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.8.9-forge"
update-url = "oneclient/generated/pvp-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cee677c50f6f71a340f8bc56a349a71025ba0244a77c9edac2ed1ae8a4118c59"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
