hash-format = "sha256"

[[files]]
file = "mods/optifine.pw.toml"
hash = "2e51c8487c8f38814a50c2ccdd9601e4a105fd1365a6e20b96ebb38629242fb9"
metafile = true

[[files]]
file = "mods/patcher.pw.toml"
hash = "82889beeca678450be32f7fe9e998845d9e5761690e756ff159367db863eda0a"
metafile = true

[[files]]
file = "mods/quickquit.pw.toml"
hash = "18981b3cc6c4c14f007c1acddf3b92308e1be81adaab7dfd5331a1de2e11b4f7"
metafile = true

[[files]]
file = "mods/rawinput.pw.toml"
hash = "45770505699608d5c872b09ddfaac9be7f984baf7500c5476c4e38552cfb78f5"
metafile = true

[[files]]
file = "mods/redirectionor.pw.toml"
hash = "028b94f15675cce4ccb5674d53b8fca48f4acce665f2dc56a5d5229ce1eb3439"
metafile = true

[[files]]
file = "mods/veloxcaelo.pw.toml"
hash = "ef2082a8f8ff9fb32d3dfcf2cbf842068ee57717bef9ccd2f5cab547f900085f"
metafile = true
