hash-format = "sha256"

[[files]]
file = "mods/optifine.pw.toml"
hash = "2e51c8487c8f38814a50c2ccdd9601e4a105fd1365a6e20b96ebb38629242fb9"
metafile = true

[[files]]
file = "mods/patcher.pw.toml"
hash = "6d7de31281f94b6c5732b9b3e6f4db61b33b8cac5f9e34e49a5dbdd6b3317ad6"
metafile = true

[[files]]
file = "mods/quickquit.pw.toml"
hash = "24e6966eab43c6e06dbb971ce34107c880b5bdfb3f06e7b88a6eda797d05642e"
metafile = true

[[files]]
file = "mods/rawinput.pw.toml"
hash = "8ae3655ac6e801de0e12e0910064099682be3f5482931aa26137fc6818ea8971"
metafile = true

[[files]]
file = "mods/redirectionor.pw.toml"
hash = "028b94f15675cce4ccb5674d53b8fca48f4acce665f2dc56a5d5229ce1eb3439"
metafile = true

[[files]]
file = "mods/veloxcaelo.pw.toml"
hash = "7eef8bd27de9f434875bee5ae4fbf2a3b1d4f731696574615a9ebb271a4e0403"
metafile = true
