name = "OneClient 1.8.9 Forge [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.8.9-forge"
update-url = "oneclient/generated/performance-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a55bec86908c3511320c0272c946e24dd0800c5af45f9134769786fb8f19b0df"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
