name = "OneClient 1.8.9 Forge [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.8.9-forge"
update-url = "oneclient/generated/performance-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8c5b604aea65ff2cbf25e31218226a9a7be447dc0f95eb44a368700370e7929"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
