name = "OneClient 1.8.9 Forge [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.8.9-forge"
update-url = "oneclient/generated/performance-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a8f8fe30d37f968b5997db7c550f538c2703b106fed9c54726a60ddfe056a3a"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
