hash-format = "sha256"

[[files]]
file = "mods/bazaar-utils.pw.toml"
hash = "abc30cf3aec119702c027309a523e9e7459e55f43bb261a76e22555c71b51a78"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "208c801e334a46912969bb47b0e21cc503e8a8fc75aa7d0aea85b9d32d7207ae"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "98e963bf5542d3bfec0eda3ec7b013b490b100a6098cd197dd24e6b0474179f0"
metafile = true

[[files]]
file = "mods/firmament.pw.toml"
hash = "012ee5daf3b8ccf4a4f6fa0a3706500db06c7aa4a749332cc64728d47d8aa4b9"
metafile = true

[[files]]
file = "mods/hsm.pw.toml"
hash = "ccec111363e0abab666413ba1a4708c81f944a258317a946bc9d686223f23c76"
metafile = true

[[files]]
file = "mods/hypixel-mod-api.pw.toml"
hash = "616b130437626bea38cc7d5b896b8b0004e9b168b363313b997ab8eee5bc1e7a"
metafile = true

[[files]]
file = "mods/legacyskyblock.pw.toml"
hash = "24fcd6e893efd45abdbe1a6f082344e76c0d3ead3fc4cbb20b575ee1e2dacd0a"
metafile = true

[[files]]
file = "mods/modern-warp-menu.pw.toml"
hash = "9309236c7270dbaf2918be38431351de6afd4131ff71bef9987b3aca07516efc"
metafile = true

[[files]]
file = "mods/sbt.pw.toml"
hash = "c73902b993be8dfade98e836628354aa5e625855b78000bb58662f8165d81446"
metafile = true

[[files]]
file = "mods/skyblock-custom-scoreboard.pw.toml"
hash = "d597c67dc145114397bdd0174d2ae78a027e7276655d121e3f915ff3b53d0c15"
metafile = true

[[files]]
file = "mods/skyblock-profile-viewer.pw.toml"
hash = "1c870c3df00dae9a39d0e96e78702f628d82d09600b7a3aad80629e0bcc968a0"
metafile = true

[[files]]
file = "mods/skyblock-rpc.pw.toml"
hash = "21a7c3108af49d7e505b758a8884198dcdb56626dd1d2b09184fa9f5fdeb2216"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "1047663f0ae61e051562646b4a95c7d8a0e8b4b8fe7cc05a428e59baadbbf79a"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "9684839ef0dfdbc9f58d5d328f3d36ab03c78fd8a495b98ea03f176aabd69479"
metafile = true

[[files]]
file = "mods/skycubed.pw.toml"
hash = "d20064aa39937a8e3850fefd405ff7a99b71f2972a914b3c48cf8875ad10ef69"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "cb82b73250590996270ef56a5cd4d0839063654bf36ef773bc8d59c91b59d5ab"
metafile = true

[[files]]
file = "mods/skyocean.pw.toml"
hash = "90cf9d2b22d30de93b5566a6e321b449c1237f3059cbf6634310202e02ef9a77"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1eb89ac2f78826052a7096368ee166836356939e1a139788c2d828f0b44a8371"
metafile = true
