hash-format = "sha256"

[[files]]
file = "mods/bazaar-utils.pw.toml"
hash = "663f59ee16b92a87eef6077705d9f13f4e5ccd3b0a7343212d3568760d491416"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "436fece36e8837e8922762b74763f5600d0190d36c5f7974b02cc06a78a95c7b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "4c1e84bb95c1b6955ed51373e41ab9b58a89bbdac3119c0b0fdd04edbb1ffd6d"
metafile = true

[[files]]
file = "mods/firmament.pw.toml"
hash = "a62047f5d472c6412c102d5c38f2812d07661338ed42bd7ccb418f8fc3a9f15c"
metafile = true

[[files]]
file = "mods/hsm.pw.toml"
hash = "459a5515e9246e361e61d8b3b6fb2ffda11cdd34077270fe728599dbc589631d"
metafile = true

[[files]]
file = "mods/hypixel-mod-api.pw.toml"
hash = "23fb78f56ab631dcb4f249b64feb03293f1f44e39ea65b3eba7dcd37d74be005"
metafile = true

[[files]]
file = "mods/legacyskyblock.pw.toml"
hash = "6582791994d24571274dc39b234734cef271269ca6ebaa7ad43975e9b8e041cb"
metafile = true

[[files]]
file = "mods/modern-warp-menu.pw.toml"
hash = "f203052ff5e25c2d707b7e617a80053449f193b6930450e4b3a13e63ab357aa3"
metafile = true

[[files]]
file = "mods/sbt.pw.toml"
hash = "497aa8772c0a069b5447db1b45b4c0671f3547c40f70d20c6a75cf830dd3e1f9"
metafile = true

[[files]]
file = "mods/skyblock-custom-scoreboard.pw.toml"
hash = "669e5f93fd2f5b3897df6da9a8d8c271d9a4e19ce2bb972b83c9b40372d23c6a"
metafile = true

[[files]]
file = "mods/skyblock-profile-viewer.pw.toml"
hash = "0c8a762e87552b3f4ab31bc0d8ef504044ee5869c472fc1dfe73a99a6641dd0e"
metafile = true

[[files]]
file = "mods/skyblock-rpc.pw.toml"
hash = "ec2558968e011efd3a4e9adc011f4598be09a6e0d171bba6ee194732f0779877"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "fc1ab0cc860fd196b801a51bdf370fc6ffa8f7102e2a3fc1499e05b7f68aa5d0"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "9684839ef0dfdbc9f58d5d328f3d36ab03c78fd8a495b98ea03f176aabd69479"
metafile = true

[[files]]
file = "mods/skycubed.pw.toml"
hash = "e3e8f373ff0825499bed80917728ad98cc7613f4ae9cab11fc53044ed65d3540"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "46175c402081703f5bd122e8ebcb68f4e528dac30242110a40f07f3ef4d647bd"
metafile = true

[[files]]
file = "mods/skyocean.pw.toml"
hash = "ffb9158fe90153bc1cf7dfca593e95e5db877ecb40d2163fc29515e96a66d881"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "c056d4d548afba28d6d3b6899dca94119d36b556dc72c15853f41830ba983639"
metafile = true
