hash-format = "sha256"

[[files]]
file = "mods/bazaar-utils.pw.toml"
hash = "663f59ee16b92a87eef6077705d9f13f4e5ccd3b0a7343212d3568760d491416"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "436fece36e8837e8922762b74763f5600d0190d36c5f7974b02cc06a78a95c7b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "44a1e5fe868dec8804451d967789ede66adc5491417bef88bb9108ec7a8e1a13"
metafile = true

[[files]]
file = "mods/firmament.pw.toml"
hash = "7888e6fdf01116efaca14da0ce890a870a511d0e5b1a94a2552b385e2212e1a3"
metafile = true

[[files]]
file = "mods/hsm.pw.toml"
hash = "459a5515e9246e361e61d8b3b6fb2ffda11cdd34077270fe728599dbc589631d"
metafile = true

[[files]]
file = "mods/hypixel-mod-api.pw.toml"
hash = "23fb78f56ab631dcb4f249b64feb03293f1f44e39ea65b3eba7dcd37d74be005"
metafile = true

[[files]]
file = "mods/legacyskyblock.pw.toml"
hash = "d5157e82a7b2048ce0b4fd5bfdc5c3b91432bd732bd85ee6ffa9b1871be5163e"
metafile = true

[[files]]
file = "mods/modern-warp-menu.pw.toml"
hash = "2ec6a445ce71e656b88995290f3050176bacbb4bbd94dc055fbc0d1a9fcb88c2"
metafile = true

[[files]]
file = "mods/sbt.pw.toml"
hash = "497aa8772c0a069b5447db1b45b4c0671f3547c40f70d20c6a75cf830dd3e1f9"
metafile = true

[[files]]
file = "mods/skyblock-custom-scoreboard.pw.toml"
hash = "8acba8d0a9407b675e594aa66d99ebb69f79d9ef5e6bd1db7608e462dc9cccbd"
metafile = true

[[files]]
file = "mods/skyblock-profile-viewer.pw.toml"
hash = "d5d2665059984315cbbb969a522b700ff87f873f0cbd70ff7413d4fe134220a9"
metafile = true

[[files]]
file = "mods/skyblock-rpc.pw.toml"
hash = "ec2558968e011efd3a4e9adc011f4598be09a6e0d171bba6ee194732f0779877"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "816ea298203690aa3bb3ef720a06beb68b6662fba7a511b65b4cc05796411738"
metafile = true

[[files]]
file = "mods/skycubed.pw.toml"
hash = "e3e8f373ff0825499bed80917728ad98cc7613f4ae9cab11fc53044ed65d3540"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "4a90bfc5865d3af974b655c6abb4f55474af8f3aadb8ce4978ded133798ba6c7"
metafile = true

[[files]]
file = "mods/skyocean.pw.toml"
hash = "ad5ce63ac7430e2c83a822d5de74d841ef5aa24e19f88d4ae059eee9e4b99ff1"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "46987b23d1c32199c3bb4db30ceca4a5260917a12c383e712a23f0736716a86f"
metafile = true
