hash-format = "sha256"

[[files]]
file = "mods/bazaar-utils.pw.toml"
hash = "663f59ee16b92a87eef6077705d9f13f4e5ccd3b0a7343212d3568760d491416"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "436fece36e8837e8922762b74763f5600d0190d36c5f7974b02cc06a78a95c7b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "4c1e84bb95c1b6955ed51373e41ab9b58a89bbdac3119c0b0fdd04edbb1ffd6d"
metafile = true

[[files]]
file = "mods/firmament.pw.toml"
hash = "a62047f5d472c6412c102d5c38f2812d07661338ed42bd7ccb418f8fc3a9f15c"
metafile = true

[[files]]
file = "mods/hsm.pw.toml"
hash = "459a5515e9246e361e61d8b3b6fb2ffda11cdd34077270fe728599dbc589631d"
metafile = true

[[files]]
file = "mods/hypixel-mod-api.pw.toml"
hash = "23fb78f56ab631dcb4f249b64feb03293f1f44e39ea65b3eba7dcd37d74be005"
metafile = true

[[files]]
file = "mods/legacyskyblock.pw.toml"
hash = "6582791994d24571274dc39b234734cef271269ca6ebaa7ad43975e9b8e041cb"
metafile = true

[[files]]
file = "mods/modern-warp-menu.pw.toml"
hash = "f203052ff5e25c2d707b7e617a80053449f193b6930450e4b3a13e63ab357aa3"
metafile = true

[[files]]
file = "mods/sbt.pw.toml"
hash = "497aa8772c0a069b5447db1b45b4c0671f3547c40f70d20c6a75cf830dd3e1f9"
metafile = true

[[files]]
file = "mods/skyblock-custom-scoreboard.pw.toml"
hash = "c1d97f4dff1873774dfbb3176419a98ea35f282bad37ea0aa9d4f559c5d16c14"
metafile = true

[[files]]
file = "mods/skyblock-profile-viewer.pw.toml"
hash = "0bfe4e65794e70d6fc867e653f8300f517aaee4b1de7803549f05b4e3e313725"
metafile = true

[[files]]
file = "mods/skyblock-rpc.pw.toml"
hash = "ec2558968e011efd3a4e9adc011f4598be09a6e0d171bba6ee194732f0779877"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "ba7caa6e52b51143e27b2fde744ea862060e486028399c86a923d565a1f102dd"
metafile = true

[[files]]
file = "mods/skycubed.pw.toml"
hash = "e3e8f373ff0825499bed80917728ad98cc7613f4ae9cab11fc53044ed65d3540"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "9139d4fcdf596c4b402f01ffa0f5609e7812527f1d5dec157bc55fa54cc82612"
metafile = true

[[files]]
file = "mods/skyocean.pw.toml"
hash = "ffb9158fe90153bc1cf7dfca593e95e5db877ecb40d2163fc29515e96a66d881"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "99aa97ac2385770b55de77865426e69e8344d92cfa12ce1abeab8719189350ef"
metafile = true
