name = "OneClient 1.21.8 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.8-fabric"
update-url = "oneclient/generated/skyblock-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f36771367418f16bf749e0ee1472abdf2f84b0bf5fd0516d8e2b7f66add39ea1"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
