name = "OneClient 1.21.8 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.8-fabric"
update-url = "oneclient/generated/skyblock-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a7477a50fc0dc8eaa62f275e79ae7855c89d7770b22a17c98e2078182aff990"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
