name = "OneClient 1.21.8 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.8-fabric"
update-url = "oneclient/generated/skyblock-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f125a400dbb4e225b06bf5914938c323e7307c32325f381a02b94bf1ba77df45"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"
