hash-format = "sha256"

[[files]]
file = "mods/animations.pw.toml"
hash = "d6003b4d6408db3303e0e185d40839a441be3abcb7cff7e12164d9a1ca4a059f"
metafile = true

[[files]]
file = "mods/block-overlay.pw.toml"
hash = "d62ac0d44f4715f346e5f9b58a55a1d3aaa95ba6ecd4951b593ff89f583ed231"
metafile = true

[[files]]
file = "mods/crashpatch.pw.toml"
hash = "c0973dcd87c43f809b5d469a8bba05b730ccd7e139a7b1b1fa1d17cd09f47c37"
metafile = true

[[files]]
file = "mods/hitbox.pw.toml"
hash = "190c02a50ec50f423791d7538d5603d0146298147f3945dfc0138fa0237ea6e9"
metafile = true

[[files]]
file = "mods/hypixel-autocomplete.pw.toml"
hash = "b6a613e50fa12809cd476eacfb373db2a4a39491cbcdd57b4073cba918bba8c9"
metafile = true

[[files]]
file = "mods/nick-hider.pw.toml"
hash = "99916bbe936927d04c3ff3985ee053469fd2fdac832e9657fba7d7a20ed7647e"
metafile = true

[[files]]
file = "mods/optibye.pw.toml"
hash = "91797d2fe01a1f836ac8b2738ba91011044216f7ec659e77c446dcf8ab53f199"
metafile = true

[[files]]
file = "mods/polysprint.pw.toml"
hash = "16db88d36cf9db1ba465da686b5abf4e5b9d74ea984d07c9d6081292bcdb33f7"
metafile = true

[[files]]
file = "mods/quickjoin.pw.toml"
hash = "64721606763a780ac3240b5d92210faae61bbf159b8bcc47920618f9cd5fae68"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "d1268eaf54904af62ef16712964151348fae42d43215bd6711666ca8a55f80f5"
metafile = true

[[files]]
file = "mods/resource-pack-manager.pw.toml"
hash = "522659e55009aaca4a743641e87992da7f9d9a52c96bd6e7337b5c3d210b6cd3"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "a9e2eadc461212e928094d39edc6ca7a7ce45b727dbff3989cfb86e49de49941"
metafile = true

[[files]]
file = "mods/scc.pw.toml"
hash = "91f81af2574beba660a268fcc89dcb9eeafc427c0a66715f6aaebe5b9170f000"
metafile = true

[[files]]
file = "mods/scrollable-tooltips.pw.toml"
hash = "f7aecaf715d2a6dbd027d348e8ceeef5a3ef5a90c87ede29db53651e3bd1f595"
metafile = true

[[files]]
file = "mods/scu.pw.toml"
hash = "44772f171d4a0585cd47897bbd08bb11484bca9acd14cc84d3bafcbcd58e70b9"
metafile = true
