hash-format = "sha256"

[[files]]
file = "mods/animations.pw.toml"
hash = "d6003b4d6408db3303e0e185d40839a441be3abcb7cff7e12164d9a1ca4a059f"
metafile = true

[[files]]
file = "mods/block-overlay.pw.toml"
hash = "d6a6e11fdfd62e334855ee6fa5e6149fd2e53a9f79530a5e312aed868badfdef"
metafile = true

[[files]]
file = "mods/crashpatch.pw.toml"
hash = "c0973dcd87c43f809b5d469a8bba05b730ccd7e139a7b1b1fa1d17cd09f47c37"
metafile = true

[[files]]
file = "mods/hitbox.pw.toml"
hash = "190c02a50ec50f423791d7538d5603d0146298147f3945dfc0138fa0237ea6e9"
metafile = true

[[files]]
file = "mods/hypixel-autocomplete.pw.toml"
hash = "7c4cde9f58a04fe92c08545e0ee46520b077fe021ea798104f9ab986d45d8e13"
metafile = true

[[files]]
file = "mods/nick-hider.pw.toml"
hash = "b1cbb069b612def576c9400fda3b4517ecd9c26511b7d443f6f8177cd001771e"
metafile = true

[[files]]
file = "mods/optibye.pw.toml"
hash = "91797d2fe01a1f836ac8b2738ba91011044216f7ec659e77c446dcf8ab53f199"
metafile = true

[[files]]
file = "mods/polysprint.pw.toml"
hash = "16db88d36cf9db1ba465da686b5abf4e5b9d74ea984d07c9d6081292bcdb33f7"
metafile = true

[[files]]
file = "mods/quickjoin.pw.toml"
hash = "64721606763a780ac3240b5d92210faae61bbf159b8bcc47920618f9cd5fae68"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "d1268eaf54904af62ef16712964151348fae42d43215bd6711666ca8a55f80f5"
metafile = true

[[files]]
file = "mods/resource-pack-manager.pw.toml"
hash = "34a31ca1f1e5ceffb1fa195366f53e2dfcc8c2fa48d75d28137b56b92f048c8e"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "a9e2eadc461212e928094d39edc6ca7a7ce45b727dbff3989cfb86e49de49941"
metafile = true

[[files]]
file = "mods/scc.pw.toml"
hash = "91f81af2574beba660a268fcc89dcb9eeafc427c0a66715f6aaebe5b9170f000"
metafile = true

[[files]]
file = "mods/scrollable-tooltips.pw.toml"
hash = "4147751793addb5f5c583e8a99dfdbb5720087b4bcea79bea484b4e07c518af2"
metafile = true

[[files]]
file = "mods/scu.pw.toml"
hash = "44772f171d4a0585cd47897bbd08bb11484bca9acd14cc84d3bafcbcd58e70b9"
metafile = true

[[files]]
file = "mods/tnttime-oneconfig.pw.toml"
hash = "585251830302e810aebb19eef1cce6816d077914ae5f08289f8807afd53b9179"
metafile = true
