name = "OneClient 1.8.9 Forge [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.8.9-forge"
update-url = "oneclient/generated/utility-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ecd7438b6837c893b6470977eed58a26bc1fe7a44d54aa9b26cedd74acb7259"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
