name = "OneClient 1.8.9 Forge [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.8.9-forge"
update-url = "oneclient/generated/utility-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04e862a1ffa0a61f82beee99e782e81012ac6f8249109873335f36aa2099dd1b"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
