name = "OneClient 1.8.9 Forge [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.8.9-forge"
update-url = "oneclient/generated/utility-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8253e5a4e2ac8d88b4b16bdd0fbe93dab1964102df67515af96f8de5358dcdbd"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
