name = "OneClient 1.8.9 Forge [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.8.9-forge"
update-url = "oneclient/generated/utility-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca888940fb57b4710c2eaee60b50de6b62d851476771d00460255a3478c8fa87"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
