hash-format = "sha256"

[[files]]
file = "mods/chatting.pw.toml"
hash = "fb740e78dabdd4820f2ae5c5e04bd4105fb51d5976b03d7cb9d5d2d3357ead5d"
metafile = true

[[files]]
file = "mods/craftify.pw.toml"
hash = "6022ce0b624772f599ac45b56c2a9b7dcb64ef788fdbe759bffd9555947f62da"
metafile = true

[[files]]
file = "mods/evergreenhud.pw.toml"
hash = "3933409ee7ba04ba302649015daad1a7cfdea58b003ee9e944fa99b2a1f5ddeb"
metafile = true

[[files]]
file = "mods/keystrokes.pw.toml"
hash = "ffe17b346eef6d326ffdd9bbc12827564710ee064bbd5b263bb75f5b91d3f1b2"
metafile = true

[[files]]
file = "mods/potioneffects.pw.toml"
hash = "612a2e9dbe5e9f524ae4c2054cdf7b531c86bf4086c870e89c4e24d3de8b058e"
metafile = true

[[files]]
file = "mods/reportplus.pw.toml"
hash = "4c38ba4ba7699e1fccc78dca8c95f8802cb9158972fd9116ab60555274d611eb"
metafile = true

[[files]]
file = "mods/soundsubtitles.pw.toml"
hash = "09cf8b8d96999819feb9cb07a29853c8561fa99569dda85f39e3b6ae4ecd2d4c"
metafile = true

[[files]]
file = "mods/vanillahud.pw.toml"
hash = "0ea12827579faa28d32d9d6fbfd2746879ddf47dc52c4161ac497bf499a1fe1a"
metafile = true
