hash-format = "sha256"

[[files]]
file = "mods/chatting.pw.toml"
hash = "f6dbfe10ae88adc3045784bb880ebf91addbdf2d677fa0fef74c8d24c7b603fe"
metafile = true

[[files]]
file = "mods/craftify.pw.toml"
hash = "9b6ec28390a92b07ea0ffa8212874c88d505d2725809bf199de615a246443f6f"
metafile = true

[[files]]
file = "mods/evergreenhud.pw.toml"
hash = "878832d7d77e9f885c3a31c9af816ca2d1379b5c3bff873caa236aa18c2cb4dc"
metafile = true

[[files]]
file = "mods/keystrokes.pw.toml"
hash = "13ad3cf3f6a1cae3453469784ea8ed5f8aecd37c560507bcd87341a6ae3a6c70"
metafile = true

[[files]]
file = "mods/potioneffects.pw.toml"
hash = "bb49a735cb5ade951ab2cf07b19a866c4a0332dc69909d873b259a7e78869ed8"
metafile = true

[[files]]
file = "mods/reportplus.pw.toml"
hash = "5420358624e7425f3d6a3d5cd2d2435c00bc74a384cf0b3c0aa6fe0b34f548cd"
metafile = true

[[files]]
file = "mods/soundsubtitles.pw.toml"
hash = "c571fc1970e1db41d56843fcc4cdc8564923678d9a9146d038f7ada0484d62ea"
metafile = true

[[files]]
file = "mods/vanillahud.pw.toml"
hash = "00ef365fd2bd4453e77bec58d1e06ffecb8d050b463970e59828034bc8c29473"
metafile = true
