name = "OneClient 1.8.9 Forge [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.8.9-forge"
update-url = "oneclient/generated/hud-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fe2e4b41c1eaa7ef392da8d9b47aa153089aa4d8105e8511272cb841aaf3241"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
