name = "OneClient 1.8.9 Forge [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "HUD"
id = "hud-1.8.9-forge"
update-url = "oneclient/generated/hud-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aa251b6b7b120c980f3e9522235ae7aa7afdfcd50dd57803b24adfedee4ff37"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
