hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "1769a50717cbda41b465a707781f06a44903b3121c208524a2a033fcc97c958d"
metafile = true

[[files]]
file = "mods/amecs-reborn.pw.toml"
hash = "f36163e58cbe90e412981bbd58cbccda164a7d1b48ea59cc03f77cf7ccee6a76"
metafile = true

[[files]]
file = "mods/animated-typing.pw.toml"
hash = "1e0af5615f686db9e6ec253e5d880249376396db76bc0f70aa22522ac0e49904"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "b347f0c7e30d1d95a646cac06b9d5d20f7d734ecef045b3e8aa545516445a15e"
metafile = true

[[files]]
file = "mods/better-elytra-render.pw.toml"
hash = "a781e9b9bcfb63ea525aa10a179ae29b0ad9a14608e7f6bbd8f5e5edce95934c"
metafile = true

[[files]]
file = "mods/better-screens.pw.toml"
hash = "0b970a150cc4b180fbcca7ff7a519903b13a47023d0790f2d7f6b1152123bc7d"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "c1eea05b9d38f68db0d4d5e07c5e1a43bb8fab4c2fde03b0c33595e77391c6d7"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "9e844732820e9de179163ed66c132970a3f90142f3b8abcb6a214f027c5c7b50"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "84d84e9455f2d3f4590d390e7e71e297810a4b807982875573d7c81f76362dfd"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "cb1c1b1450743e19fda7ecbae46979b9fa4e347c9a307dd76431f6be912152cc"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "7e1a4b2596c5d9b228726e1915033197d478b9d23d3a102d0acc4913d843172d"
metafile = true

[[files]]
file = "mods/confirm-disconnect.pw.toml"
hash = "3945e2684a4c287dba193a06bd2f33725c17d7fdb451227105ab7f78a969f5ee"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b685062c75972d7b38b8d6edc1861dbf028d90651b094a09961d3c467b5f6b84"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "df52a79acad3365956a57f2b33c9eb1421a66d1dbc4e6e217e0b8528bb391882"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "f80412aaa9569768739083ba7cc857ba1956c6bd62d3e8915ad74fa6bfd0c2d1"
metafile = true

[[files]]
file = "mods/crosshairtweaks.pw.toml"
hash = "0fa660d4f1d251b9d2220cb9622bf70f46800b0476087009478cb2d7032bbcbf"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "59f497040c3dec7a8bdef7242ae9a625520cd5bc1949f64031f6858299fc5442"
metafile = true

[[files]]
file = "mods/dark-graph.pw.toml"
hash = "6ea17d2471dd8d24c80d7f9abdee62f0d1969918c47805eb9d8889f378a96674"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "9497572a97551e67125f1546425f9b5d4373a9e1791b079f9029ed9b74255678"
metafile = true

[[files]]
file = "mods/droppeditemtweaks.pw.toml"
hash = "a24cbab3068a8d75eb1ca3f5019be3ce9c2c15ff077b943234560cb3d91182d7"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "15a9ae73c7a6622b38db4ab5bf5e784ef6b7ec56c3aca3df9ae9bc63bb5ebd09"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "b47037986fc9fd1f4549a4022d3ecfd53ae5cecb90c8a268facb5b51856cd45d"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "c11c9004434e3e4a00dc0773c86b6c55bf432bfa337ccd3226a995b053b0c024"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "88b7a344f095bd501056948928cf5db41dd5d3d23a0f298545cc2147cb411fd6"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "208c801e334a46912969bb47b0e21cc503e8a8fc75aa7d0aea85b9d32d7207ae"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "98e963bf5542d3bfec0eda3ec7b013b490b100a6098cd197dd24e6b0474179f0"
metafile = true

[[files]]
file = "mods/firmament-packet-fix.pw.toml"
hash = "5e23bb816bcce498aaa66b0b2220ba36e032b8e176c296f05d9c40281ebd8d62"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "55b49f056f80cbfca3cd072901d25f2785d181cddeeb301d5c255f60462a1029"
metafile = true

[[files]]
file = "mods/hypixelautotip.pw.toml"
hash = "34c42ccf03137a73e2500b76742eac7667d201bffcce46f35f959e0dd1b518ab"
metafile = true

[[files]]
file = "mods/idontwannascrollagain.pw.toml"
hash = "4d904fae956ce0875c9ceea96a59415481e6033a734698adc7f4fae80de934c3"
metafile = true

[[files]]
file = "mods/jsonem.pw.toml"
hash = "a5c6edf9cdf6b3e7303252ba2fc0789bd458887a7920e2b481ba5609c6805175"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "fe249e18bd8e54b678b98df52895a78f51d82f2cef7dc733d9dfbdafb58d81f5"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "85d7f3c9e861c3b9b69175fed4ee02ed4620e87576b5bafa299e1493817ee393"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "bf536ef08ddf4bfd0279902dd8a7098d2a92b7e60dfd869f1c174eb78f5bbdad"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "31658e52e488c32750f64ea36e34840a671af0f942e7485cb33595b357ca291c"
metafile = true

[[files]]
file = "mods/mountopacity.pw.toml"
hash = "be0c2c2adeb4f528d81cc0ea0eea75efd880c561ba86106a4d7e542df0c62851"
metafile = true

[[files]]
file = "mods/nametagtweaks.pw.toml"
hash = "4450a52e5edd491ced2b46093b45f2436dbefa0cfcaa0a6796bb886dfbc77774"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "ec10f1c8ac45723b3abced3b46ffd9eb894419fc47b294ab39b38c90f794beda"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7e26e52decdd8e538390990a9e271e0827e4239a7613c38a60cca126e3e4957d"
metafile = true

[[files]]
file = "mods/notsoessential.pw.toml"
hash = "59764a2d66e56607ac143d1853017eeeb067508fc4063480699e085f8940417e"
metafile = true

[[files]]
file = "mods/numerical-enchantments.pw.toml"
hash = "053622e92d3627f18402606730dcafebfad7f78e2ff04feacb333f1c35738a42"
metafile = true

[[files]]
file = "mods/one-click-join.pw.toml"
hash = "234faf4ffa8c83b98106e440206bb079234c90149bea6297999c87bcac259cd5"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "579932d8ff17b11d57c0a407328999fad1dd0cf8a4e4b13c0aa47bb13e2ec724"
metafile = true

[[files]]
file = "mods/overlaytweaks.pw.toml"
hash = "6f62f00768b2d49736f430de302cce1bb65c3a6e92f4f2a8c2c968650ef5a38e"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "e7d10c066ee475b3f4894773b6c4bb901814a397009f6e70d1add16e47bd8821"
metafile = true

[[files]]
file = "mods/particle-tweaks.pw.toml"
hash = "f84c6f948deba25ef1d73ba8fdaf9dc9b910056afb021fa23a53fd9a9099393f"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "3179dfa1675952985667d3c9969ac834b7cf9f8093fcd02be728bee4b91d2f3f"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "58f84d4ec0d11246a430817e92fda8b1c7f7f3caa0015b4eb030445fb42026d6"
metafile = true

[[files]]
file = "mods/rendertweaks.pw.toml"
hash = "c6dba165b7bddbea53074f072694bd8beb7b016cdf139d2282e7526d68a4e3bc"
metafile = true

[[files]]
file = "mods/reward-claim.pw.toml"
hash = "1722d00b99dfb783bc160683dd8db4db92a0df93ff4d7dadbfc7216abc17dc0a"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "ae0a89609ef8dec0b2297fa51a089bd8e783de216bf5f9339c96ba203260bc41"
metafile = true

[[files]]
file = "mods/scoreboardtweaks.pw.toml"
hash = "6c8cdd959a240905875ae7f699c529534c2f9fbf8d28372b0d2aa861bfb6f3a0"
metafile = true

[[files]]
file = "mods/screencopy.pw.toml"
hash = "1286090509d0c5d2e84b434940c036c06dbc96636d7d4941369c51a40a48a479"
metafile = true

[[files]]
file = "mods/scrolltweaks.pw.toml"
hash = "b388da17ff7f44332f534565ce8cbff232b8d8bbf06c84daaf467fe5d69b8bcf"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "05095acf8d6e4264b383d3edb1b6ef8a281436b80129f254f34cf16b5d568300"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "ba206189311792c2258aea66c7a2769bfd36a520435a796b6df1ff6a50b16e08"
metafile = true

[[files]]
file = "mods/simple-nick-hider.pw.toml"
hash = "03af458205604fbb5328aa67ff030d4a508eff9f34f42a00a7ab82fb93feaa16"
metafile = true

[[files]]
file = "mods/smooth-scrolling-refurbished.pw.toml"
hash = "37b5f141fa7bca687c71a5180a78e693c2b8e6ea319de836c3d2f01be9530956"
metafile = true

[[files]]
file = "mods/smooth-skies.pw.toml"
hash = "6279427ea68c5797ac7259c7eef89b7837869864ccf93768fe61756b08ce4526"
metafile = true

[[files]]
file = "mods/smuc.pw.toml"
hash = "27ebe966070a007132ebaee0122277b83a2754c6f807d1932d8d2bb6d563e84e"
metafile = true

[[files]]
file = "mods/sound-physics-perfected.pw.toml"
hash = "7473424f8d82946b2e7f442862eeea4866f3f62b670ac85803d5ac3133ad6c1f"
metafile = true

[[files]]
file = "mods/symbol-chat.pw.toml"
hash = "be444182070853378dc8121e48d4ccb5f06c08190e50eb4cee43324d46aabc41"
metafile = true

[[files]]
file = "mods/tabtweaks.pw.toml"
hash = "0f4e864103f48ea879dca137f0723bc1f97263b6978b65b1be02f18dfb07ae63"
metafile = true

[[files]]
file = "mods/text-tunnels.pw.toml"
hash = "8caae4a7d6d2a938907737f0ace3eb75dea461604645fc6a07c014c4ce9cd0d8"
metafile = true

[[files]]
file = "mods/titletweaks.pw.toml"
hash = "5e8601f3f1eacf1cc495b5b26996ecd9826a13b226d74e1566b530a992c845de"
metafile = true

[[files]]
file = "mods/tntime.pw.toml"
hash = "1bf9fd6fae556436d8f8753f4518f11395a0af13ad4a7899da632fc9467e23a0"
metafile = true

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "53c67bde30c9912c04c610aa333963ebc0c8e01ea768a34d88dfcb8a681af92b"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "31fa9034a0c41b21d99d429883ea2788c4b70608199c58a78b0f607d0ed294e5"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "afe1e569e97f2578adcca71131d887bb75c6e58b018d748ea7a493976b094539"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e5dd08cfbb73958f614c7e2611de05194fc6adba6c4e0931a520412b1f0c6676"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3a0cfb6034a14d65f050278d2580c7166a895e7a37d8e512e2cc9deadba74107"
metafile = true
