name = "OneClient 1.21.8 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.8-fabric"
update-url = "oneclient/generated/qol-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d04288d42f5cf3a5506d406cb8f5601a791e677546bb5527c7505f388d63cec"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
