name = "OneClient 1.21.8 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.8-fabric"
update-url = "oneclient/generated/qol-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3321a47a3632539b2157eccfdba8a1fef332dea4c71d6fb7c1410974221386f"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
