hash-format = "sha256"

[[files]]
file = "mods/apec.pw.toml"
hash = "113a7466b8e913e8a426544414f9d056232eb2c88f2207f0a88a0fe24904ae5f"
metafile = true

[[files]]
file = "mods/bazaarnotifier.pw.toml"
hash = "29a2d57095e98b1e981937537becfd47584fff76d269ca197d69b02798841aaf"
metafile = true

[[files]]
file = "mods/chattriggers.pw.toml"
hash = "a31cc708911f2a33a914287c54d35d023e97f721b9fa9e51e91be22f1ff7cf87"
metafile = true

[[files]]
file = "mods/cowlection.pw.toml"
hash = "3a58c2e6394af9088cec813710fbbf8a9be107ebf9108a239a3b5dcedd3b975d"
metafile = true

[[files]]
file = "mods/dankers-skyblock-mod.pw.toml"
hash = "f5066dec7c0bbf002d1b34ff31322f86e27e756f04543d1d35d5b0b698c9ab7c"
metafile = true

[[files]]
file = "mods/dungeonroomsmod.pw.toml"
hash = "af9cd34d344c63e17e334a461044e53c4628d2ac1ff592ecffbae8cfb7cd7941"
metafile = true

[[files]]
file = "mods/dungeons-guide.pw.toml"
hash = "efa82157c5bf9d39a62afb6f40309c6bc9b32ee2e1deb5312cd036b335cb1381"
metafile = true

[[files]]
file = "mods/fancy-warp-menu.pw.toml"
hash = "3e22bc0875e84f3f02ba94827f2c09bf06e485e0e6e7c7c7ca75cb367304a469"
metafile = true

[[files]]
file = "mods/notenoughupdates.pw.toml"
hash = "66db6dcdbe0dee5ef887741d1ed9cd929e6141e8d394b69e68ac46cc0c598b9a"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "9aed01829e028fb8c621e04194f2c871a881c17ebd802cd687b8492f911fa14e"
metafile = true

[[files]]
file = "mods/partly-sane-skies.pw.toml"
hash = "fbf9e8baf1f55a0e93f87b0593993788e78dbec9733e076b5cfdfd1f40cd54df"
metafile = true

[[files]]
file = "mods/scatha-pro.pw.toml"
hash = "5971148075fb1fd0a178f54693128cc29652858084999808f0cd69c351289c29"
metafile = true

[[files]]
file = "mods/scrollable-tooltips.pw.toml"
hash = "f7aecaf715d2a6dbd027d348e8ceeef5a3ef5a90c87ede29db53651e3bd1f595"
metafile = true

[[files]]
file = "mods/secret-routes-mod.pw.toml"
hash = "1deecba30ae37400ca6a5224b8dd7ceb0185ed2ad80234ff20321d222c656e8a"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "fd812e9c5176547a7f78e9d1dc499e414a12daaaef5afb0fd67535d1548786f5"
metafile = true

[[files]]
file = "mods/skyblockhud.pw.toml"
hash = "44aa45b547aec3a55c4ca4eb11fa3e0dd4b679eea022af9f3de8a4786169a7c6"
metafile = true

[[files]]
file = "mods/skyblockpersonalized.pw.toml"
hash = "779aabfc2c1046b52147ba29d86a8ae0d7137e03b18da3c6e22715aa3c3b2fe5"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "5f701a98cf367474d116f8446b84364971f309eac3b40c25243ea2b47b1caf72"
metafile = true

[[files]]
file = "mods/skyguide.pw.toml"
hash = "643b607661ea302362444aa0bc20e40761cd3d993a29ae9a63529454f87afa63"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "d18ba75dcbd39a250e4eddff71cc9d1af7c75c3f1c2d999624d83cf08e85159d"
metafile = true

[[files]]
file = "mods/skytils.pw.toml"
hash = "effb6ec0575128f139ed7479fa88fc4fb4b98b070243d7fd877d68b5d97346d6"
metafile = true
