hash-format = "sha256"

[[files]]
file = "mods/apec.pw.toml"
hash = "a5bba815c4a897ab645b022be4923bbb9149a5a24aa134b3324ecd9f2d416e44"
metafile = true

[[files]]
file = "mods/bazaarnotifier.pw.toml"
hash = "0fec8cc46627f03ed9f0e49f557c5e1a2f15befde60b9c3584cbee460a847ae7"
metafile = true

[[files]]
file = "mods/chattriggers.pw.toml"
hash = "16ce993bccd9bf00eb1e704bb773bda87ca834ee35767290264d604132b24cfd"
metafile = true

[[files]]
file = "mods/cowlection.pw.toml"
hash = "04ceb3e4d4950210d1eed3da7b19f56b3522068d68a6e24b4ce80d705ee09b56"
metafile = true

[[files]]
file = "mods/dankers-skyblock-mod.pw.toml"
hash = "5ea1034cdd8542e8f29e018aef137bf734ef88039e143d548db188af85f9159a"
metafile = true

[[files]]
file = "mods/dungeonroomsmod.pw.toml"
hash = "45aa072a799473e7fd7c7189a156fc33939c6cde8c1614c9478c957317030782"
metafile = true

[[files]]
file = "mods/dungeons-guide.pw.toml"
hash = "0dec89507172364298a5db00137858b6ed7a6a2f1edd236c20cdf0a7bdcc091d"
metafile = true

[[files]]
file = "mods/fancy-warp-menu.pw.toml"
hash = "3e22bc0875e84f3f02ba94827f2c09bf06e485e0e6e7c7c7ca75cb367304a469"
metafile = true

[[files]]
file = "mods/notenoughupdates.pw.toml"
hash = "d1de78cd19ce74b1dece68c8daf561600b9c7c0f6df1dc480e2bd892845d3dbe"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "7a3561100a1c88678a71fe0ab8a106c975273ead0087a1aec65049edafbb2e06"
metafile = true

[[files]]
file = "mods/partly-sane-skies.pw.toml"
hash = "744040d28198e240c5d1bc4654fc9fa890d428a88838efb0350a1fdf5192f726"
metafile = true

[[files]]
file = "mods/scatha-pro.pw.toml"
hash = "31841458c3ad0f937daf2936806edd821cd81f3e7f5e2ab04335cd0566dbaa5e"
metafile = true

[[files]]
file = "mods/scrollable-tooltips.pw.toml"
hash = "1d60a9a4e2288748fd19952df849a460b784fba245a1d83d7817c5e460ec0e1e"
metafile = true

[[files]]
file = "mods/secret-routes-mod.pw.toml"
hash = "3cc5270ced9ba784ee333924c344ab8221fd1e859087dc00445fbec138f4f614"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "fd812e9c5176547a7f78e9d1dc499e414a12daaaef5afb0fd67535d1548786f5"
metafile = true

[[files]]
file = "mods/skyblockhud.pw.toml"
hash = "b0340b82bf26440249883cc1ceb2b894e429ea61d812e4b31c66c35edadb2674"
metafile = true

[[files]]
file = "mods/skyblockpersonalized.pw.toml"
hash = "f3fb024e0de6801faacaf6abcc2425415252dc3b351d94bac0c4abeebbd03aab"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "5f701a98cf367474d116f8446b84364971f309eac3b40c25243ea2b47b1caf72"
metafile = true

[[files]]
file = "mods/skyguide.pw.toml"
hash = "2344da783effa8dfe5177e2ce6c497c140f871c825ebd81ba58620a294f468bf"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "d18ba75dcbd39a250e4eddff71cc9d1af7c75c3f1c2d999624d83cf08e85159d"
metafile = true

[[files]]
file = "mods/skytils.pw.toml"
hash = "94cfa8f55abdfabe9ca504fb9323c1d140b6ab2bd57068d4150afa95222a87ef"
metafile = true
