hash-format = "sha256"

[[files]]
file = "mods/apec.pw.toml"
hash = "a5bba815c4a897ab645b022be4923bbb9149a5a24aa134b3324ecd9f2d416e44"
metafile = true

[[files]]
file = "mods/bazaarnotifier.pw.toml"
hash = "14cb11caab5a75a52b7aed752eeb6d0837855042c800db8ae0caffb2c6f54ced"
metafile = true

[[files]]
file = "mods/chattriggers.pw.toml"
hash = "16ce993bccd9bf00eb1e704bb773bda87ca834ee35767290264d604132b24cfd"
metafile = true

[[files]]
file = "mods/cowlection.pw.toml"
hash = "5009c933e88edd118f7893f4f78d8d8e057619ad342cd94f7e8cf0e58850b87a"
metafile = true

[[files]]
file = "mods/dankers-skyblock-mod.pw.toml"
hash = "dd146edaed58f1b8e9f0aab9b10d17c02801e4e1f21f3bee09d79ddcd85df8d3"
metafile = true

[[files]]
file = "mods/dungeonroomsmod.pw.toml"
hash = "cbbfd2cf6d9b8e63411186fb3f29b9c2bc2bce1d16c20ae8afb688ef5ea28a83"
metafile = true

[[files]]
file = "mods/dungeons-guide.pw.toml"
hash = "0dec89507172364298a5db00137858b6ed7a6a2f1edd236c20cdf0a7bdcc091d"
metafile = true

[[files]]
file = "mods/fancy-warp-menu.pw.toml"
hash = "92438fc8feea95cc9d9026de6460f027b67de33b3b70037296115e429b576a0a"
metafile = true

[[files]]
file = "mods/notenoughupdates.pw.toml"
hash = "d1de78cd19ce74b1dece68c8daf561600b9c7c0f6df1dc480e2bd892845d3dbe"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "7a3561100a1c88678a71fe0ab8a106c975273ead0087a1aec65049edafbb2e06"
metafile = true

[[files]]
file = "mods/partly-sane-skies.pw.toml"
hash = "744040d28198e240c5d1bc4654fc9fa890d428a88838efb0350a1fdf5192f726"
metafile = true

[[files]]
file = "mods/scatha-pro.pw.toml"
hash = "31841458c3ad0f937daf2936806edd821cd81f3e7f5e2ab04335cd0566dbaa5e"
metafile = true

[[files]]
file = "mods/scrollable-tooltips.pw.toml"
hash = "6f845638ebc3d4faf271e7498486441908057514b7d52636e1ce10d486f4e5e2"
metafile = true

[[files]]
file = "mods/secret-routes-mod.pw.toml"
hash = "3cc5270ced9ba784ee333924c344ab8221fd1e859087dc00445fbec138f4f614"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "b4093592a34411d15ce1f038bdea49776e5c3ac708ac0065c231fe442176aca6"
metafile = true

[[files]]
file = "mods/skyblockhud.pw.toml"
hash = "ebfd0ac1c75f04d98e98521928f479b62e6bfe83c5ae3080329aaf6eae90c4db"
metafile = true

[[files]]
file = "mods/skyblockpersonalized.pw.toml"
hash = "57600c171a51f1d57ff6538faac3a83a4f80ea26f3c231312a69b485e64cbaf7"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "4558c5b91a8d294dec260b919104faf5c5c6b6c9cff20b928581579a4c872c00"
metafile = true

[[files]]
file = "mods/skyguide.pw.toml"
hash = "2344da783effa8dfe5177e2ce6c497c140f871c825ebd81ba58620a294f468bf"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "f7efc5d3ab374493c14e96e463defa1fc7689de590d878f48172acc0e41db15d"
metafile = true

[[files]]
file = "mods/skytils.pw.toml"
hash = "63036d98a560e0622900532c8a1143f689173115ec7a760e61afdefb1db704cd"
metafile = true
