hash-format = "sha256"

[[files]]
file = "mods/apec.pw.toml"
hash = "113a7466b8e913e8a426544414f9d056232eb2c88f2207f0a88a0fe24904ae5f"
metafile = true

[[files]]
file = "mods/bazaarnotifier.pw.toml"
hash = "d020b49172f9c7b54d8173ec5f46fdfa5df61b6d39a17e0af61a15cbb4d445c4"
metafile = true

[[files]]
file = "mods/chattriggers.pw.toml"
hash = "a31cc708911f2a33a914287c54d35d023e97f721b9fa9e51e91be22f1ff7cf87"
metafile = true

[[files]]
file = "mods/cowlection.pw.toml"
hash = "bbecc373eecf2faa966e19860f1f7116faa7678de9a024240bd587ce2f5a592e"
metafile = true

[[files]]
file = "mods/dankers-skyblock-mod.pw.toml"
hash = "f5066dec7c0bbf002d1b34ff31322f86e27e756f04543d1d35d5b0b698c9ab7c"
metafile = true

[[files]]
file = "mods/dungeonroomsmod.pw.toml"
hash = "93065e507b0c525c4d250072d7b95f6efe3ff0539e7257cea3c0016560f746f1"
metafile = true

[[files]]
file = "mods/dungeons-guide.pw.toml"
hash = "efa82157c5bf9d39a62afb6f40309c6bc9b32ee2e1deb5312cd036b335cb1381"
metafile = true

[[files]]
file = "mods/fancy-warp-menu.pw.toml"
hash = "3e22bc0875e84f3f02ba94827f2c09bf06e485e0e6e7c7c7ca75cb367304a469"
metafile = true

[[files]]
file = "mods/notenoughupdates.pw.toml"
hash = "66db6dcdbe0dee5ef887741d1ed9cd929e6141e8d394b69e68ac46cc0c598b9a"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "9aed01829e028fb8c621e04194f2c871a881c17ebd802cd687b8492f911fa14e"
metafile = true

[[files]]
file = "mods/partly-sane-skies.pw.toml"
hash = "fbf9e8baf1f55a0e93f87b0593993788e78dbec9733e076b5cfdfd1f40cd54df"
metafile = true

[[files]]
file = "mods/scatha-pro.pw.toml"
hash = "5971148075fb1fd0a178f54693128cc29652858084999808f0cd69c351289c29"
metafile = true

[[files]]
file = "mods/scrollable-tooltips.pw.toml"
hash = "1d60a9a4e2288748fd19952df849a460b784fba245a1d83d7817c5e460ec0e1e"
metafile = true

[[files]]
file = "mods/secret-routes-mod.pw.toml"
hash = "1deecba30ae37400ca6a5224b8dd7ceb0185ed2ad80234ff20321d222c656e8a"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "fd812e9c5176547a7f78e9d1dc499e414a12daaaef5afb0fd67535d1548786f5"
metafile = true

[[files]]
file = "mods/skyblockhud.pw.toml"
hash = "5317d6d74724b301f15b45fc14636d9e81fe8e7abe970728badb56f096425272"
metafile = true

[[files]]
file = "mods/skyblockpersonalized.pw.toml"
hash = "55f79e0ef34fd55e40c62e23ba8d038667fe6c0e0a0db7875fb1957d1a5908a9"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "5f701a98cf367474d116f8446b84364971f309eac3b40c25243ea2b47b1caf72"
metafile = true

[[files]]
file = "mods/skyguide.pw.toml"
hash = "643b607661ea302362444aa0bc20e40761cd3d993a29ae9a63529454f87afa63"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "d18ba75dcbd39a250e4eddff71cc9d1af7c75c3f1c2d999624d83cf08e85159d"
metafile = true

[[files]]
file = "mods/skytils.pw.toml"
hash = "041538244abddb45051b9fb62b019b7dcdef9be7897a5eded453d7afac06004b"
metafile = true
