hash-format = "sha256"

[[files]]
file = "mods/apec.pw.toml"
hash = "a5bba815c4a897ab645b022be4923bbb9149a5a24aa134b3324ecd9f2d416e44"
metafile = true

[[files]]
file = "mods/bazaarnotifier.pw.toml"
hash = "0fec8cc46627f03ed9f0e49f557c5e1a2f15befde60b9c3584cbee460a847ae7"
metafile = true

[[files]]
file = "mods/chattriggers.pw.toml"
hash = "16ce993bccd9bf00eb1e704bb773bda87ca834ee35767290264d604132b24cfd"
metafile = true

[[files]]
file = "mods/cowlection.pw.toml"
hash = "04ceb3e4d4950210d1eed3da7b19f56b3522068d68a6e24b4ce80d705ee09b56"
metafile = true

[[files]]
file = "mods/dankers-skyblock-mod.pw.toml"
hash = "5ea1034cdd8542e8f29e018aef137bf734ef88039e143d548db188af85f9159a"
metafile = true

[[files]]
file = "mods/dungeonroomsmod.pw.toml"
hash = "45aa072a799473e7fd7c7189a156fc33939c6cde8c1614c9478c957317030782"
metafile = true

[[files]]
file = "mods/dungeons-guide.pw.toml"
hash = "0dec89507172364298a5db00137858b6ed7a6a2f1edd236c20cdf0a7bdcc091d"
metafile = true

[[files]]
file = "mods/fancy-warp-menu.pw.toml"
hash = "92438fc8feea95cc9d9026de6460f027b67de33b3b70037296115e429b576a0a"
metafile = true

[[files]]
file = "mods/notenoughupdates.pw.toml"
hash = "d1de78cd19ce74b1dece68c8daf561600b9c7c0f6df1dc480e2bd892845d3dbe"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "7a3561100a1c88678a71fe0ab8a106c975273ead0087a1aec65049edafbb2e06"
metafile = true

[[files]]
file = "mods/partly-sane-skies.pw.toml"
hash = "744040d28198e240c5d1bc4654fc9fa890d428a88838efb0350a1fdf5192f726"
metafile = true

[[files]]
file = "mods/scatha-pro.pw.toml"
hash = "31841458c3ad0f937daf2936806edd821cd81f3e7f5e2ab04335cd0566dbaa5e"
metafile = true

[[files]]
file = "mods/scrollable-tooltips.pw.toml"
hash = "a03af8e0ba7179ca92cd3384662874395fce6c93f7efa88c96859efe26950620"
metafile = true

[[files]]
file = "mods/secret-routes-mod.pw.toml"
hash = "3cc5270ced9ba784ee333924c344ab8221fd1e859087dc00445fbec138f4f614"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "b4093592a34411d15ce1f038bdea49776e5c3ac708ac0065c231fe442176aca6"
metafile = true

[[files]]
file = "mods/skyblockhud.pw.toml"
hash = "b0340b82bf26440249883cc1ceb2b894e429ea61d812e4b31c66c35edadb2674"
metafile = true

[[files]]
file = "mods/skyblockpersonalized.pw.toml"
hash = "f3fb024e0de6801faacaf6abcc2425415252dc3b351d94bac0c4abeebbd03aab"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "52d003b1087f97723ba8892ee35b72937549ad2e88d43f46395fcdcdd4a05f3f"
metafile = true

[[files]]
file = "mods/skyguide.pw.toml"
hash = "2344da783effa8dfe5177e2ce6c497c140f871c825ebd81ba58620a294f468bf"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "f7efc5d3ab374493c14e96e463defa1fc7689de590d878f48172acc0e41db15d"
metafile = true

[[files]]
file = "mods/skytils.pw.toml"
hash = "94cfa8f55abdfabe9ca504fb9323c1d140b6ab2bd57068d4150afa95222a87ef"
metafile = true
