hash-format = "sha256"

[[files]]
file = "mods/apec.pw.toml"
hash = "a5bba815c4a897ab645b022be4923bbb9149a5a24aa134b3324ecd9f2d416e44"
metafile = true

[[files]]
file = "mods/bazaarnotifier.pw.toml"
hash = "29a2d57095e98b1e981937537becfd47584fff76d269ca197d69b02798841aaf"
metafile = true

[[files]]
file = "mods/chattriggers.pw.toml"
hash = "16ce993bccd9bf00eb1e704bb773bda87ca834ee35767290264d604132b24cfd"
metafile = true

[[files]]
file = "mods/cowlection.pw.toml"
hash = "3a58c2e6394af9088cec813710fbbf8a9be107ebf9108a239a3b5dcedd3b975d"
metafile = true

[[files]]
file = "mods/dankers-skyblock-mod.pw.toml"
hash = "5ea1034cdd8542e8f29e018aef137bf734ef88039e143d548db188af85f9159a"
metafile = true

[[files]]
file = "mods/dungeonroomsmod.pw.toml"
hash = "af9cd34d344c63e17e334a461044e53c4628d2ac1ff592ecffbae8cfb7cd7941"
metafile = true

[[files]]
file = "mods/dungeons-guide.pw.toml"
hash = "0dec89507172364298a5db00137858b6ed7a6a2f1edd236c20cdf0a7bdcc091d"
metafile = true

[[files]]
file = "mods/fancy-warp-menu.pw.toml"
hash = "92438fc8feea95cc9d9026de6460f027b67de33b3b70037296115e429b576a0a"
metafile = true

[[files]]
file = "mods/notenoughupdates.pw.toml"
hash = "d1de78cd19ce74b1dece68c8daf561600b9c7c0f6df1dc480e2bd892845d3dbe"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "7a3561100a1c88678a71fe0ab8a106c975273ead0087a1aec65049edafbb2e06"
metafile = true

[[files]]
file = "mods/partly-sane-skies.pw.toml"
hash = "744040d28198e240c5d1bc4654fc9fa890d428a88838efb0350a1fdf5192f726"
metafile = true

[[files]]
file = "mods/scatha-pro.pw.toml"
hash = "31841458c3ad0f937daf2936806edd821cd81f3e7f5e2ab04335cd0566dbaa5e"
metafile = true

[[files]]
file = "mods/scrollable-tooltips.pw.toml"
hash = "f7aecaf715d2a6dbd027d348e8ceeef5a3ef5a90c87ede29db53651e3bd1f595"
metafile = true

[[files]]
file = "mods/secret-routes-mod.pw.toml"
hash = "3cc5270ced9ba784ee333924c344ab8221fd1e859087dc00445fbec138f4f614"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "b4093592a34411d15ce1f038bdea49776e5c3ac708ac0065c231fe442176aca6"
metafile = true

[[files]]
file = "mods/skyblockhud.pw.toml"
hash = "44aa45b547aec3a55c4ca4eb11fa3e0dd4b679eea022af9f3de8a4786169a7c6"
metafile = true

[[files]]
file = "mods/skyblockpersonalized.pw.toml"
hash = "779aabfc2c1046b52147ba29d86a8ae0d7137e03b18da3c6e22715aa3c3b2fe5"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "52d003b1087f97723ba8892ee35b72937549ad2e88d43f46395fcdcdd4a05f3f"
metafile = true

[[files]]
file = "mods/skyguide.pw.toml"
hash = "2344da783effa8dfe5177e2ce6c497c140f871c825ebd81ba58620a294f468bf"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "f7efc5d3ab374493c14e96e463defa1fc7689de590d878f48172acc0e41db15d"
metafile = true

[[files]]
file = "mods/skytils.pw.toml"
hash = "effb6ec0575128f139ed7479fa88fc4fb4b98b070243d7fd877d68b5d97346d6"
metafile = true
