hash-format = "sha256"

[[files]]
file = "mods/apec.pw.toml"
hash = "a5bba815c4a897ab645b022be4923bbb9149a5a24aa134b3324ecd9f2d416e44"
metafile = true

[[files]]
file = "mods/bazaarnotifier.pw.toml"
hash = "6b30c9dcc138f4e0dcc41b712fa9a0b1237e80519e055d53c1794c0e9f9786a0"
metafile = true

[[files]]
file = "mods/chattriggers.pw.toml"
hash = "16ce993bccd9bf00eb1e704bb773bda87ca834ee35767290264d604132b24cfd"
metafile = true

[[files]]
file = "mods/cowlection.pw.toml"
hash = "ea0533017b36dc64db2c430024c2e00f9142908d297a494d3451c5a33a87e6b9"
metafile = true

[[files]]
file = "mods/dankers-skyblock-mod.pw.toml"
hash = "7792c60cfbfa94c589e86087356fa25b50258a2393182947f5463af6636f79cc"
metafile = true

[[files]]
file = "mods/dungeonroomsmod.pw.toml"
hash = "ab41539a43ef0f85f194c753c7c2af8c9ea6b17926c78db0a9ef06dd917ee9e0"
metafile = true

[[files]]
file = "mods/dungeons-guide.pw.toml"
hash = "0dec89507172364298a5db00137858b6ed7a6a2f1edd236c20cdf0a7bdcc091d"
metafile = true

[[files]]
file = "mods/fancy-warp-menu.pw.toml"
hash = "3e22bc0875e84f3f02ba94827f2c09bf06e485e0e6e7c7c7ca75cb367304a469"
metafile = true

[[files]]
file = "mods/notenoughupdates.pw.toml"
hash = "d1de78cd19ce74b1dece68c8daf561600b9c7c0f6df1dc480e2bd892845d3dbe"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "7a3561100a1c88678a71fe0ab8a106c975273ead0087a1aec65049edafbb2e06"
metafile = true

[[files]]
file = "mods/partly-sane-skies.pw.toml"
hash = "744040d28198e240c5d1bc4654fc9fa890d428a88838efb0350a1fdf5192f726"
metafile = true

[[files]]
file = "mods/scatha-pro.pw.toml"
hash = "31841458c3ad0f937daf2936806edd821cd81f3e7f5e2ab04335cd0566dbaa5e"
metafile = true

[[files]]
file = "mods/scrollable-tooltips.pw.toml"
hash = "1d60a9a4e2288748fd19952df849a460b784fba245a1d83d7817c5e460ec0e1e"
metafile = true

[[files]]
file = "mods/secret-routes-mod.pw.toml"
hash = "3cc5270ced9ba784ee333924c344ab8221fd1e859087dc00445fbec138f4f614"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "fd812e9c5176547a7f78e9d1dc499e414a12daaaef5afb0fd67535d1548786f5"
metafile = true

[[files]]
file = "mods/skyblockhud.pw.toml"
hash = "99cfb6a37878d0e88b7c2f8b55f09a5a751757d73966b5354bfda1ef81d40a92"
metafile = true

[[files]]
file = "mods/skyblockpersonalized.pw.toml"
hash = "68442d5cf1bdbdb413e93bae6db7be4aaa14db0eea892a50ea0f6b6a171264be"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "5f701a98cf367474d116f8446b84364971f309eac3b40c25243ea2b47b1caf72"
metafile = true

[[files]]
file = "mods/skyguide.pw.toml"
hash = "2344da783effa8dfe5177e2ce6c497c140f871c825ebd81ba58620a294f468bf"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "51413f150c151357c3c1f55c7ab4495c48dff2503db1cb6a77bdedc25f02ac5c"
metafile = true

[[files]]
file = "mods/skytils.pw.toml"
hash = "1042b8020b57ef927bf3321ac9fbf755f2d07d6fdeb0d5b2d3c6ee7a639f5340"
metafile = true
