hash-format = "sha256"

[[files]]
file = "mods/apec.pw.toml"
hash = "113a7466b8e913e8a426544414f9d056232eb2c88f2207f0a88a0fe24904ae5f"
metafile = true

[[files]]
file = "mods/bazaarnotifier.pw.toml"
hash = "c6a6e7eea1ad924c4aff979eb83e68405b5e4e57cc217dc498a91287580eed8f"
metafile = true

[[files]]
file = "mods/chattriggers.pw.toml"
hash = "a31cc708911f2a33a914287c54d35d023e97f721b9fa9e51e91be22f1ff7cf87"
metafile = true

[[files]]
file = "mods/cowlection.pw.toml"
hash = "628e72b820ee199f6181d216930c6ab96a9be609081fa06a594181e4d266a366"
metafile = true

[[files]]
file = "mods/dankers-skyblock-mod.pw.toml"
hash = "f5066dec7c0bbf002d1b34ff31322f86e27e756f04543d1d35d5b0b698c9ab7c"
metafile = true

[[files]]
file = "mods/dungeonroomsmod.pw.toml"
hash = "970e07c8caa37cbc7302108d2ac733761d77b06a46109136b0391b5e11091d9f"
metafile = true

[[files]]
file = "mods/dungeons-guide.pw.toml"
hash = "efa82157c5bf9d39a62afb6f40309c6bc9b32ee2e1deb5312cd036b335cb1381"
metafile = true

[[files]]
file = "mods/fancy-warp-menu.pw.toml"
hash = "3e22bc0875e84f3f02ba94827f2c09bf06e485e0e6e7c7c7ca75cb367304a469"
metafile = true

[[files]]
file = "mods/notenoughupdates.pw.toml"
hash = "66db6dcdbe0dee5ef887741d1ed9cd929e6141e8d394b69e68ac46cc0c598b9a"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "9aed01829e028fb8c621e04194f2c871a881c17ebd802cd687b8492f911fa14e"
metafile = true

[[files]]
file = "mods/partly-sane-skies.pw.toml"
hash = "fbf9e8baf1f55a0e93f87b0593993788e78dbec9733e076b5cfdfd1f40cd54df"
metafile = true

[[files]]
file = "mods/scatha-pro.pw.toml"
hash = "5971148075fb1fd0a178f54693128cc29652858084999808f0cd69c351289c29"
metafile = true

[[files]]
file = "mods/scrollable-tooltips.pw.toml"
hash = "1d60a9a4e2288748fd19952df849a460b784fba245a1d83d7817c5e460ec0e1e"
metafile = true

[[files]]
file = "mods/secret-routes-mod.pw.toml"
hash = "1deecba30ae37400ca6a5224b8dd7ceb0185ed2ad80234ff20321d222c656e8a"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "fd812e9c5176547a7f78e9d1dc499e414a12daaaef5afb0fd67535d1548786f5"
metafile = true

[[files]]
file = "mods/skyblockhud.pw.toml"
hash = "dc27824f299ba3bb6d2dd6366ad9980e5a99b78add853e225e1c27e03a681af4"
metafile = true

[[files]]
file = "mods/skyblockpersonalized.pw.toml"
hash = "c2a4095bbb63b5df9bd87ff0ddb3508bb360b4863c32552db9a720b88b1f68d3"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "5f701a98cf367474d116f8446b84364971f309eac3b40c25243ea2b47b1caf72"
metafile = true

[[files]]
file = "mods/skyguide.pw.toml"
hash = "643b607661ea302362444aa0bc20e40761cd3d993a29ae9a63529454f87afa63"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "51413f150c151357c3c1f55c7ab4495c48dff2503db1cb6a77bdedc25f02ac5c"
metafile = true

[[files]]
file = "mods/skytils.pw.toml"
hash = "98f7103a6f4f37e5a4faf7d4c164f165b18f5b3c429f821dec343c56b0a29b56"
metafile = true
