hash-format = "sha256"

[[files]]
file = "mods/apec.pw.toml"
hash = "cab1963aca907b46ecc699c3b4ff2ccdcd81662f550a3e8af100cbb6510eaedb"
metafile = true

[[files]]
file = "mods/bazaarnotifier.pw.toml"
hash = "7c193d7b84c1091d7b7857f80a4ec8480b3c6383abe323ec3d35527b9b2935cf"
metafile = true

[[files]]
file = "mods/chattriggers.pw.toml"
hash = "80cf491bcff905ef0bffcb62349836c99d3701a121fad93ce1c18eee3331fb34"
metafile = true

[[files]]
file = "mods/cowlection.pw.toml"
hash = "dec4b9909a44586e9be9a17d06c12b974249003bdb9c17fa7628bad6b087f5cd"
metafile = true

[[files]]
file = "mods/dankers-skyblock-mod.pw.toml"
hash = "d324ec3ef6643744579603faca8d7ba8d87145556e3387cdfa27c3b580869d67"
metafile = true

[[files]]
file = "mods/dungeonroomsmod.pw.toml"
hash = "a737ff968a32d1529b7a2dbcdbaa57f920a1df1f4acd6caff40660ea2d6dd2dd"
metafile = true

[[files]]
file = "mods/dungeons-guide.pw.toml"
hash = "a7699e15e44ff12c88cbe8ad7e991a08f856274a0256eb2dce0a089704c31d09"
metafile = true

[[files]]
file = "mods/fancy-warp-menu.pw.toml"
hash = "3e22bc0875e84f3f02ba94827f2c09bf06e485e0e6e7c7c7ca75cb367304a469"
metafile = true

[[files]]
file = "mods/notenoughupdates.pw.toml"
hash = "66db6dcdbe0dee5ef887741d1ed9cd929e6141e8d394b69e68ac46cc0c598b9a"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "9aed01829e028fb8c621e04194f2c871a881c17ebd802cd687b8492f911fa14e"
metafile = true

[[files]]
file = "mods/partly-sane-skies.pw.toml"
hash = "5dc2b8031038724c1dd3ad63a882f86966f08995fe7dad5238d56ea0a0a657ee"
metafile = true

[[files]]
file = "mods/scatha-pro.pw.toml"
hash = "1f5a1dbd47877bae7f04f720a12adb6ea886ed5672aa4e66a30b09fc29e61c32"
metafile = true

[[files]]
file = "mods/scrollable-tooltips.pw.toml"
hash = "f7aecaf715d2a6dbd027d348e8ceeef5a3ef5a90c87ede29db53651e3bd1f595"
metafile = true

[[files]]
file = "mods/secret-routes-mod.pw.toml"
hash = "1198b076fd72f3ed23473a79a93bc4769f115d345be69a792f2edda1f8a3c9e5"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "fd812e9c5176547a7f78e9d1dc499e414a12daaaef5afb0fd67535d1548786f5"
metafile = true

[[files]]
file = "mods/skyblockhud.pw.toml"
hash = "e5d950d132ee77524052e1a0cf460d065ebf2208458bb244ba0ee7c22949d28b"
metafile = true

[[files]]
file = "mods/skyblockpersonalized.pw.toml"
hash = "12da8449dbe591e4f632bd4181d98e96a413183d140ba345ab6cefed96a5b000"
metafile = true

[[files]]
file = "mods/skycofl.pw.toml"
hash = "aef20a7d7d162e6e2a7e5b674ac10ce027f9995d52b5166c8acc4c7fc6736b3d"
metafile = true

[[files]]
file = "mods/skyguide.pw.toml"
hash = "0af9435eac93c65ba0a88e68c940fe65e397141b4e92b212f5cecb1650526b9c"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "61297a4598bbac21902c40a90ab2fbe8f8c0e0257aa94bd8a082cbbb903320eb"
metafile = true

[[files]]
file = "mods/skytils.pw.toml"
hash = "26cc478d1f76259a154f0678a2fca6c921e9dd949a4a231909f9d51e222b385c"
metafile = true
