name = "OneClient 1.8.9 Forge [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.8.9-forge"
update-url = "oneclient/generated/skyblock-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "956ab104fcb3b0ed830390ea5096224ea6bd4944b18ae11b0212fc12ece6caad"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
