name = "OneClient 1.8.9 Forge [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.8.9-forge"
update-url = "oneclient/generated/skyblock-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a4017a3bc6d8926d30b0a3aaf2199973b4fe9d62f7eb9f766b2c08b4ac3f663"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
