name = "OneClient 1.8.9 Forge [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.8.9-forge"
update-url = "oneclient/generated/skyblock-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d3dc40f92dff83785d8e05a7da0eddf94cbf53e171f865d5354040d16f622ae"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
