name = "OneClient 1.8.9 Forge [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.8.9-forge"
update-url = "oneclient/generated/skyblock-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08c5dd7529f9ef14c53db48b3549a2aa6f01f266faaf8bceffc5f5c8b7fac520"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
