name = "OneClient 1.8.9 Forge [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.8.9-forge"
update-url = "oneclient/generated/skyblock-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4efc43aeac6389cc96834f12c122ec2f15dad89ba80746d732c101e7c0be5f73"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
