name = "OneClient 1.8.9 Forge [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.8.9-forge"
update-url = "oneclient/generated/skyblock-1.8.9-forge.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca57be6717a3a89260a5555df896d89f1f6459a94c2b89f9c4944d2b585b4b6f"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
