hash-format = "sha256"

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e1207ff71f5a6b65ef08c05e3446cb6e63d3880bf7b5f08171d788167bf5a611"
metafile = true

[[files]]
file = "mods/effecttimerplus.pw.toml"
hash = "3e82cf9a015fef6062e43a5d1a47655dcd64f88362e2afde42e04a7a51a99229"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0ccdc424f79a941e9666fafa82520e7f3946b227c8ea3888e94c026cb7dd4f1a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "a60191aea3632a323b53598905c500349564f767d5a919ceca946b81f854c8d4"
metafile = true

[[files]]
file = "mods/no-ones-view-model.pw.toml"
hash = "b3a703dc35f3914389767bb4364a831a74c442a91a15eb71a41aacd5e3b3dda8"
metafile = true

[[files]]
file = "mods/shaketweaks.pw.toml"
hash = "a3d5b9eaf4a22c8b99237f16127b8ce974ef3dc8932fe31dad29933d46c765d1"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
hash = "2f7c6a9df79fa2cc6e7e2a455c4ac06ec3d523081803e6f04d3a90e450e75a3a"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "56f8f259d696e2d370ea3ad21b4db02bb3c8a8bcdeb04a27861fb1550f033748"
metafile = true
