name = "OneClient 1.21.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.1-fabric"
update-url = "oneclient/generated/pvp-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d055fb3f84e186b10d5c5a831e36b2ea43e486013d0f8831a8aed833711c8bf"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
