hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "79bf24f530719464df93ae6e573f6ef21c5158d191a83fba144f9fca16cdbc23"
metafile = true

[[files]]
file = "mods/amecs-reborn.pw.toml"
hash = "ca78f6636396e1e4fac4d5269228a69a1df94851355df229ab921c626ca14b0f"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "40a4454573d8a9dc636925848723c884f2bb920daa7a43495bbbb187e090e756"
metafile = true

[[files]]
file = "mods/better-selection.pw.toml"
hash = "c1eea05b9d38f68db0d4d5e07c5e1a43bb8fab4c2fde03b0c33595e77391c6d7"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "9dd35a7d7da34fe1970ffa2d069a0f9f24036d0f995096555654b3bd0e427c01"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "99bf27e0e172294692a749541247be512c6f8e62cbcc04b8d1de2c318cb9f541"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "22b475f20f599d7bc1f3a42bf721a7b2f0aeaadf445b21af822f510d4778b93d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e1207ff71f5a6b65ef08c05e3446cb6e63d3880bf7b5f08171d788167bf5a611"
metafile = true

[[files]]
file = "mods/confirm-disconnect.pw.toml"
hash = "5d7a2610b33c70b517b2962fd5f4bba48c6bef3398f7a1daf35d1eca076ecac9"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "69e3a45925376a3d36fd60ae8939157f4e9644d3697323fbe74f295f77869bd3"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "f38bd18f021b719b4c4d76cfdfcf5ebbcce1f467a822cf963a94fa9f6faa64ce"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "2f7794d9414aab544b9e10d12f3c3f18f28808568655017583c2f2905d6773a9"
metafile = true

[[files]]
file = "mods/crosshairtweaks.pw.toml"
hash = "be00a5533d988bf23bffb1dd5e06d36d3f1dfd4be35f1d7f4a06015d310709cd"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "f8bd5d466d93b970b8d2e7a475445104d6b9424a11bb10b5e78cd551655a9bdf"
metafile = true

[[files]]
file = "mods/dark-graph.pw.toml"
hash = "ec90b584060eabf68cec1e36e025fcb7d760f84e3164ac9eaf04d97176a32c02"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "96916cd5fb48372e8f1a4bb8a40bc5b32432c6037048200d484902bf0613ff62"
metafile = true

[[files]]
file = "mods/droppeditemtweaks.pw.toml"
hash = "3390d4ae1e2ba7aab927ab9a234d31fe9b63d3764609f858f02ebe53182ec167"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "15a9ae73c7a6622b38db4ab5bf5e784ef6b7ec56c3aca3df9ae9bc63bb5ebd09"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "64082ece2ec9e585ff282f56e4fc7c37d1c92e76f1539729fe2d99e5007003e0"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "14154189944bec8243c8558cbed129de69777c6b7ac0ca7409700562bc943bd3"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "72a87fc6bc2e3ea8be4fa47dd6eeb11007eb2a7301a58c5abdcaf31138e4979b"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0ccdc424f79a941e9666fafa82520e7f3946b227c8ea3888e94c026cb7dd4f1a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "98e963bf5542d3bfec0eda3ec7b013b490b100a6098cd197dd24e6b0474179f0"
metafile = true

[[files]]
file = "mods/hypixelautotip.pw.toml"
hash = "34c42ccf03137a73e2500b76742eac7667d201bffcce46f35f959e0dd1b518ab"
metafile = true

[[files]]
file = "mods/idontwannascrollagain.pw.toml"
hash = "3e0d4557b36386c0433db0fb76d80aaba50f66b76652f18cc3dc42c4e5b9a713"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "85d7f3c9e861c3b9b69175fed4ee02ed4620e87576b5bafa299e1493817ee393"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d5e879c15ae557652903aec3afd7b0bffd5001f771dc7cc13975a6ba5544c3a9"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "a60191aea3632a323b53598905c500349564f767d5a919ceca946b81f854c8d4"
metafile = true

[[files]]
file = "mods/mountopacity.pw.toml"
hash = "294c392f0ff4c4d9dca63dac1a3e777557942dfaa1bf1c86f4d02f9b551d9e00"
metafile = true

[[files]]
file = "mods/nametagtweaks.pw.toml"
hash = "333011e193e47d3fd06fd6a4ec05c2c3fdb3ac0814110868630c8373254051a6"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "15cddbbb41fb0ac09fbcf85d2bdc7c28be3b804d87ac5b9d15f8b6992b80cf9c"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7b9512d934d6842bfa1dfee2f2a95fdc686c828033349749725a4d2428232b49"
metafile = true

[[files]]
file = "mods/notsoessential.pw.toml"
hash = "59764a2d66e56607ac143d1853017eeeb067508fc4063480699e085f8940417e"
metafile = true

[[files]]
file = "mods/numerical-enchantments.pw.toml"
hash = "95cfa1b19a7bd02bd38ce69ee46e97b2de99261c9a5c921d99fc30cc21bd9932"
metafile = true

[[files]]
file = "mods/one-click-join.pw.toml"
hash = "942cd8d7dea97e94ee2b09fc0fbe50909349a003b9b8c0825449e8ba4c3e5f9c"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "4397f77fe26812dc57f79e00bc16db4ebdf302f7e787b574e82664a64954d40e"
metafile = true

[[files]]
file = "mods/overlaytweaks.pw.toml"
hash = "bbcf262a088f06135e3ddec11d472ec99ff4b14f35c8fa6981286644549cbdc3"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "ff5395950c56bf1c0b3f98ded12f28f0ef54ac5088218124d646590e36b669b6"
metafile = true

[[files]]
file = "mods/particle-tweaks.pw.toml"
hash = "31b110bd8f35a312cfa59556fe477292cf1ac796ceb8380c2f26934f5aa2dc54"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "c1d5f47f74e1eccf378ec23067f639ec806d4ff02e32a40bf7952d1a472f3921"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "dea2b50438d4c20245e5b0956cffae80cfc016d7f4ae7e12b3546706aae98812"
metafile = true

[[files]]
file = "mods/rendertweaks.pw.toml"
hash = "25e0c2f3a07d14b9818db4688efc8ffc56e109e8db5fc235d5f1b940e51557e3"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "e6b1679e6c7096174467b9d0c42feb5bc0beb5ef78616e47bdd55a06f214be95"
metafile = true

[[files]]
file = "mods/scoreboardtweaks.pw.toml"
hash = "54a3bac8cc7bbedd1cddfc51c0f016026d00d06832e64f7aef89c04f4d3a8390"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "875547da72b123db8c660568b3542d767c5ed2b4a54c66d7bf68b358da0123b6"
metafile = true

[[files]]
file = "mods/scrolltweaks.pw.toml"
hash = "cebc96dfaaf022cd294d8784bc2040dc86253f567ee113ca3244d094a3aaf397"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "019591dfc17895503ed8b0fc89478849fc6f2106580ee6906d60657f005388c8"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "ba206189311792c2258aea66c7a2769bfd36a520435a796b6df1ff6a50b16e08"
metafile = true

[[files]]
file = "mods/simple-nick-hider.pw.toml"
hash = "03af458205604fbb5328aa67ff030d4a508eff9f34f42a00a7ab82fb93feaa16"
metafile = true

[[files]]
file = "mods/smooth-scrolling-refurbished.pw.toml"
hash = "5caf598abc608642c64e9a30f0a0b307a39baa7bf9fc36bcd44862c525ccb966"
metafile = true

[[files]]
file = "mods/smooth-skies.pw.toml"
hash = "371a781958070b2b2ba84d2d141b29b85b0dd3de3d8aa88de35f71072c7bc5f1"
metafile = true

[[files]]
file = "mods/smuc.pw.toml"
hash = "27ebe966070a007132ebaee0122277b83a2754c6f807d1932d8d2bb6d563e84e"
metafile = true

[[files]]
file = "mods/sound-physics-perfected.pw.toml"
hash = "1920fadd64b8ebd272546e529e1ab24e86872a857ca8f4b49f0ff2502136d6ee"
metafile = true

[[files]]
file = "mods/symbol-chat.pw.toml"
hash = "edb7717ea021b7637b62c2c8d1af530b757e729d2b5ff68c372a5ab3c944af77"
metafile = true

[[files]]
file = "mods/tabtweaks.pw.toml"
hash = "f5eb4d95935f23a39fa118e4514d647f1e8380863ff42f15d00ded7d23bbd323"
metafile = true

[[files]]
file = "mods/text-tunnels.pw.toml"
hash = "917d1451b537cc8e76207d104a6fc7433d2fe0880a04ed86a96791d79bfb9a3f"
metafile = true

[[files]]
file = "mods/titletweaks.pw.toml"
hash = "40fafdbf13eddf4832836ac600b6fdab5f5e824779fb786998e2cf91e29057c0"
metafile = true

[[files]]
file = "mods/tooltip-scroll.pw.toml"
hash = "41ade38f0fa4c8d09a60144b30666b7c07b95ca3e501df74d7ac63a2d9b9fced"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "a4827a216fb085ace2761de5b4b77395331d7d94a948f87248356271b82dc4e2"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "b215847aa86b3b6573524373288f5bef9b5d2c41f6f06296c3886e674b1c0178"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "56f8f259d696e2d370ea3ad21b4db02bb3c8a8bcdeb04a27861fb1550f033748"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3a0cfb6034a14d65f050278d2580c7166a895e7a37d8e512e2cc9deadba74107"
metafile = true
