name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f95e1b8417a9d2a67b55b9435f97ce78f9ecd54af0208b733e0f3953e5084fef"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
