name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e9e18ae3f34e013f400a5d81e9df65a4eda45260d963b0ad28aeda1493b8ac5"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
