name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11f2ca14596426b10bc2969a430eb32687936be9966da67b15fbf3ba5c64c3ff"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
