name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29a106a66a947652b7a4ecc9d1d5b84c0747c99c337c300ea7e112a97b5619b9"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
