hash-format = "sha256"

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "53dc6e7d85703ac953f0762c8831aac1e894e731892960adc2bcc8dd46dcb24d"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "e5addaf572a739e71774db0e1074500f28d5200adc302cb203c444412b3702bd"
metafile = true

[[files]]
file = "mods/better-mipmaps.pw.toml"
hash = "5047af072387a574c86b39bcba310b141325a4125b30d9caf3d64b78722618c0"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "649a59aa346908990b4b8952ac8a373d1a12526da01e6557a8eefb01332dbf45"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "76b6fda698cdd336a97069ad637d51a1687cad4f9e3fa393dca7464531320280"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "88fa3d3592b32664d0c0c30823747d71b8ebd55eb7eb949149bdf29d93115179"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "a6063c5799e03f0b71be5630873f513d995bd90e07b1c761cd250f7250b3fab3"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "211ea261a6d703268a408a6161a01e96011133221b4df2bbfdb3aba3b1d44404"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "abaa638502723ac6e47e7e142e2f1444ad8ef0a7253180c480e3d62fb091b51e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "ceeb74701686102e584e233755eb84ac56d30ec1a3e297b1b940dcf58575a041"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "4c1e84bb95c1b6955ed51373e41ab9b58a89bbdac3119c0b0fdd04edbb1ffd6d"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "c821b4e7c30c4f590066c21f46d4720f9e83814b35629afe4fa469eed2a844fc"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "44d59f075f9fefa236ab748e1e3081a8afb125b21abd14bdbab2fd7ab8ff6516"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "017fdd6a76eed9e87775113b7d31b98e8c7c996baf4ad5aeaa6dc7fc2e428d29"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "a6be0d290ca6903988d05df68e1548f6cf21f8203608ab7c2bddad00f558e2ee"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "8468ef1035f07565477b113e75ebe8ef69f7af7f8dbc736391d2b4480fd98d0a"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "b54da35777a4f3bf83ce8f464bac275493aa79c37330fd93c1d02fafba3bcda1"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "3534ffe104e765d4398de1ff2b469f2658c05915346dda1ccfdd0331390f98c1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "b68f720afbed1635277cb98433d200502cafe7ef6b328dd2a0b7d7ec63f02ed3"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "3229ae8429589e02efccb52d63633c491afd344cc4bac4e911cfd21e4baa5191"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "b42583a75545a95bedb079b0aba323fcfcd207d5d59546a230059c15b71e4a23"
metafile = true

[[files]]
file = "mods/lazy-language-loader.pw.toml"
hash = "3641d59a00394aff2aec7caea7909bc27eb5d33ea25da3a83857c0c8ee996fe9"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0adf8ea75c577af41e8dfa665d712a03183770fbe195eb38297872605876cb11"
metafile = true

[[files]]
file = "mods/log-cleaner.pw.toml"
hash = "6a11f24debd05247a8df11859d78ace5c775fd82e8b8ae27b1ce3a8bc73234b1"
metafile = true

[[files]]
file = "mods/modernfix-fabric-5.20.4-beta.54+mc1.21.8.c05a.jar"
hash = "09db495c7031be8d5e34242cb188bf569469eba5a23fa70bf66a4c07d7f98a07"

[[files]]
file = "mods/modmenu.pw.toml"
hash = "a9e2dd8c0765780684783ed4413bba1ffbbf757a431323d1d0b7480329f1fb98"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "3f56a40eed2a7a8c3504deeb67528040e57d4fce725d407366e6c2061f3f5833"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "51cfa88e5a17e7391cd6b075b46bd39ea3a8de634ada545c001e4c0b6921ad89"
metafile = true

[[files]]
file = "mods/optipainting-updated.pw.toml"
hash = "41530c4ed8ad8f364e2d61d6a9b81989d8ba1817691ad0095a5ed76c546401aa"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "a7e28d19cd344c09414ed65c23605623e478479625a23b4d371556ee9e4ed6be"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "0018700cff68eb5c13e70d5a49e24df1b518a89caf5af7015ea1130cfea45ac3"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "84708938e26fea5f42e188b79e8a576ee9da8c4071063359008e0a2259ebf1b6"
metafile = true

[[files]]
file = "mods/sciophobia.pw.toml"
hash = "c597d6945e6f508a01092197c2756866ad5707e031060f166884a914dc4f96b7"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "dce1b022c9baf13e0ce2d8d4767b0b1f558d87582fbd96a8e1867f394b926890"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "516438841015101d7ab17cede366218ccfc2f22fedecd9a2fb10d68782e24df4"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "4993d985b6e79f6282b5fc7844d36baa0c0efaf02e54fc924bcd05e7a9a9604e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "c056d4d548afba28d6d3b6899dca94119d36b556dc72c15853f41830ba983639"
metafile = true
