hash-format = "sha256"

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "2f607512aeff0ebb9ff109b47a66f715c581113f639c75ad45887b2c7af12510"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "ec15cc4c12c2dcfe34c28a5eca4da6fdf359bfc730376b53d85766fa9e70cebb"
metafile = true

[[files]]
file = "mods/better-mipmaps.pw.toml"
hash = "5ccbefab308f9ff809bced92e81c1719e7b13196ff0b39d0711bcfafeb5bfdce"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "b5d783ec28815d00db1c9171827d854a6694593d3911881b1147f048d9273480"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "7e1a4b2596c5d9b228726e1915033197d478b9d23d3a102d0acc4913d843172d"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "b7cf0af8e6ebe28032c5094fda6a9de904d9ed1866a7bf6b0191b3d390c0d047"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "2163f68f926fd153d3719877c16ca860c3ca436a11dd27890fadab53a26c9e06"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "42a5e2a28d70a4835eae49333529eb2215717e0f6738fb9339f15763189bad9d"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "497b5575ac9a34b44585f12c2189346312c9e4f9473f47ae7234d89d55fc8a84"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "410d6b08384c4e34177063fc8261c5bc88b77b8fc779c5ac0aa67d400429c4b9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "98e963bf5542d3bfec0eda3ec7b013b490b100a6098cd197dd24e6b0474179f0"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "816ade73e66a97360755d8083e7ecea6f693482119c522ef32788e1d4bf7f697"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "c2fa3fc181b2657213b3371d6a3d0ad8e93548935ea4dec7e4b29d9588d91d0b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1648127006afe22d16098ba4d3ffc33379ea88dac210e73a67cc20c2ad8f55c1"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "e0a5061283c7084745ec0594b235ff33b1fd199af023a2dd6ba56f5d2fd26ee9"
metafile = true

[[files]]
file = "mods/forcecloseworldloadingscreen.pw.toml"
hash = "0d5b1a55d64419fc5cfc5fce74fa4d862ef2e3eca5161791b6ca26186f9e18c6"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "7973d30ebbb721997158f5454b4901ced67130f518ca61e237d971df06ef4f88"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "862f9016be4c12c3566732560812f39a4627fb73d70eaf7c3d37651c74db85f3"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "98ada593311f703dfdb34845160bcddee1e47011cccb22f0004951572ff9307d"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "653a02ae726473c9d08d58e566f06f8964279f4f570d3f66bd112f2711172bb5"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "04282532f8341a731298609dd4f3ac56059f65602853c9dc6bd89cefbac59c0a"
metafile = true

[[files]]
file = "mods/lazy-language-loader.pw.toml"
hash = "16445f70eed1fdf8f8667597a7afd13b84b535ccd67ac2d848d6bd2e1bea4497"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "d10fc0e77a7db2f4c3b0226e0fcd034a06161e73f4ff58478be7f1c0e6706067"
metafile = true

[[files]]
file = "mods/log-cleaner.pw.toml"
hash = "ee38b691291acc163d76aa0b602c82af0f1bac571ed189bcbb81cd7fb4ea19be"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "9176100cc75f16a61923898c72e47a01259a27bfb2d10909a28822495024169b"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "31658e52e488c32750f64ea36e34840a671af0f942e7485cb33595b357ca291c"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "ae6abca5e64e5ec2c355c9d3a7673524e13c9f77781b3959a9f68fdf0a0390ef"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "b6ae0abbf459f48df6344089c87ec5fd9fd3c1ad052124dc49fa6ec1dc60ec9f"
metafile = true

[[files]]
file = "mods/optipainting-updated.pw.toml"
hash = "43fba1c07cc51cf4f389586bee6b641c965b1ad87f052cd71b3da35f3ae2cc37"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "28cc5bae276154237431db136320e0fb2e8807f0b24fff7efa435ca4d4cc132f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4c1f60da2aef5557bfe6fbfb0e83db919b6054fb89173e2a2de9b23b8b83fc1c"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "ed4c8f982fa2f3aa309938adb02c6d8c78f0e529beb2e7153f35c31841babd64"
metafile = true

[[files]]
file = "mods/sciophobia.pw.toml"
hash = "df208738ff710620b33a7e91b850507490a47552248c86449994175d1bcc5f4f"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "5a113012ddf7470cc7897d5828a6dc398a6b17f4464169274f606a6d6390fb4a"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "31fcf960f0d6f1f21111bdb5a61fd09a07c6140a83ad4f1aee486c7a34cabdcc"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "361a3833233a1ae1476a8104ca39170af0f098a4bd168b610015c68a1f4257c1"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1eb89ac2f78826052a7096368ee166836356939e1a139788c2d828f0b44a8371"
metafile = true
