name = "OneClient 1.21.8 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.8-fabric"
update-url = "oneclient/generated/performance-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "282bcd224b08c5f0c91bce738f00ad681aefbc2e8c2c0b1427ea1f24d262da4a"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
