name = "OneClient 1.21.8 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.8-fabric"
update-url = "oneclient/generated/performance-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74adcceb5b52d91cfa39cbdf74322b9fcc609ffcebda8a99dc6763afc385d130"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
