hash-format = "sha256"

[[files]]
file = "mods/animatium.pw.toml"
hash = "6e480e5f7658a8139b16e7493f8cd33bbe695d10f84fc63d4e6191a67b550c42"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "dbc4960d91ef836961171d8a13f8adc29ee6df2c63ea23efeca96fc93e5d280a"
metafile = true

[[files]]
file = "mods/audio-engine-tweaks.pw.toml"
hash = "2c1a6d7c0fc9e011dd5c618d592057f4cc377fdce230fe553e3853410044485d"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "c2dd467cc5398d147a3b0bef54c022b945f30d7e0217c87d716121f7e8d1d67a"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "230fd9f75b3c7b1777bd186762bedf1af9fceb7673dbbb75342d930dbea012fc"
metafile = true

[[files]]
file = "mods/betternightvision.pw.toml"
hash = "a80e53a334ee3bd4c2ac4f06cf156a7843c91953e3724d7b0a64484010c68c1d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9c22bad4f0d606f92ce105da00204c29aa2b356401cc5d1088f63bb02f90d351"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "2982ba68df71ad328abfe668c6cbc73e0712d75a37c7685ec293096dc46b962c"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "09c9be9ebe431cfa8f80b921f17d2fd84947c754ff3eaa6fcf61c79470728fdf"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "77ae21ed913af83ad741b7c54d3d6a9201cbc891dd6d2e0741d77c21f3ae0b7f"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "11e043bf815b74a2cf1ca826e550e6e9aa10aea4830f853e49760a299df4f752"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "71057ffacb79edc48ef50b33ba506255e3da4ad48e8d0eaa4635368097567ba9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "44a1e5fe868dec8804451d967789ede66adc5491417bef88bb9108ec7a8e1a13"
metafile = true

[[files]]
file = "mods/frozenlib.pw.toml"
hash = "bdf6fa532b9526f8f0592c3a1bf53b76e31221e832b7dac827d4c7d89b5c8285"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "61eb4c52a94a2716fba0a47109eff44951aa70fa3f618cc64a072e8561c59105"
metafile = true

[[files]]
file = "mods/hypixelautogg.pw.toml"
hash = "5378bdb84fa219bcdd76718c5539a22fb443f3441d721fc91c27f805dc2eb4ad"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "b3129bfd9b9bb373f96b7e08ca1981f8e2f69fdadf9d3ff1118c97f3f8e93ba1"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "89989b99381b7616a1145920824ba63990142d019fc1cc784c34d4d6c5ff86fa"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "85465e9b6f11189e6a30acb2c830499d9c5f71fe676d88b5890748f52a19eafc"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c4e6161d6670b5a508ab683f59f792ea265043d31608e4d7923977e239df5853"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "d3e8051165c4403238d0c53e3070c4de69e42714f33d5e9ee59ff02aef06c0b9"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "f02298e202c5cbe4c771f5e2dd8835db7e020e36935e108a0b3e46637b7b335f"
metafile = true

[[files]]
file = "mods/rei-search-bar-calculations.pw.toml"
hash = "7878cb066e70a052ea5fed1ad3f827b182db6214ae4589caf892c48b93ea507a"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "824c6168bd8b313f19c171186b4bccf5d8556c54d1642302dd4b5e6e2ba0eb00"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "6bc856b9161651d5e236022f11116d5334c2231ec14755a726ee00e9ae90cc40"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "394b9225fb333c8bb3c57a654f85675850556d9d3d01d1c95cc3e6a6f75d609a"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "1bd6e16679d23e6691f119e3f7d5c6c3c424b7ec0c64d3b10bd5b88e4c1e0204"
metafile = true

[[files]]
file = "mods/simple-block-overlay.pw.toml"
hash = "70ba3cdfdea9e099786f8d5f0c722592f466c59e696e9848aa6baaac71e415b6"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "eae7c1fcb9f1fa128fc8f09f2c8eca3e512ad77ba1d3b7c2bd1ec64c33b20a01"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "6e0f414996a0e52109a89bcd70fa7e2192471bc02b6258fa25c279b69030e0e5"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "1a8c765b8b5b81b375e6fb9019005cf59d79b9f079a17ac1859acdfc2bf3ac6e"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "f2908d9033570d993a21f671304f08edb7696d65260b58e2b55d0c943f9b172c"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "1a53fd9a425b727d9f3b867b77c92755bc0ef387619c6947b8b64d6fc0782c7a"
metafile = true

[[files]]
file = "mods/toggle-toggle-sprint.pw.toml"
hash = "c8f603f98338f7e5e2844d6b5375491d8d0abbf99fe1c0ff952d1530cc44e5c2"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "96121ed08a26a8415c16686e73fe8f7a4e4591c61552d772aa3784a4f8d3c5bb"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "2ca97b27bad39520f5d4828f0fcafc66a3c34632197e239c2b44578667d50e77"
metafile = true
