hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "b57435e07f00cc154940bd0bdbc0c4909031d6212465a2b6a5b68283bc3b599e"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "955e7437e9a64d43ff4a3ec650b4811c7ac8304cd7d2fdfbf16c00a7df10df13"
metafile = true

[[files]]
file = "mods/chat-impressive-animation.pw.toml"
hash = "26a1f483e37770f6e9dd86eea1977f09d440bb4116a2035cd2ffbf9584febf5c"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "e6f3a27eab5b12be66feb1df09eac29fbedb33d254f85c182235ec12ea19989a"
metafile = true

[[files]]
file = "mods/clean-f3.pw.toml"
hash = "288269e2aff73ea5adc4eda51bc797d0d8e6046469e5382bb115743359b8d1c6"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "37892a1101fb31f445c6c9e913e5090fc7dc4d7949f6856effbeafd62ef80d01"
metafile = true

[[files]]
file = "mods/detail-armor-bar.pw.toml"
hash = "55def88e464ef42c00af38e69a97100f0154be9c6c878fd9cf50872c49bb78b1"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "d6fa16a0824b7bec0b2e3438fba995dbcddb6586bdec71e7aeca5bf58e199a88"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "786f3a6ed629e1bafd211366b13b12d1d38a5769244391c218cdc39c895fca04"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "f3cf24f6f5cb8572c0006d3f8aaaa3e743468c5afac9de40eb07cdbdb5e7463f"
metafile = true

[[files]]
file = "mods/tiptapshow.pw.toml"
hash = "fff13e17bc4721a50170a6ceb523a8da57917cf42138d7466db5d35ba4b6e967"
metafile = true

[[files]]
file = "mods/ukulib.pw.toml"
hash = "20e1a1dcf94d75727bdc6794ddd91fd05eedd8ab0c74e47ebb10ad4b4d9de0f7"
metafile = true

[[files]]
file = "mods/ukus-armor-hud.pw.toml"
hash = "b645d09fcdae9e6a47209869d0a40e7dce8e8395b6fbf74091a7c9ab989f9777"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "cff1e44974ed93fb60101173bddf5bd52f6ff72a4de55ceacec82af5fd903a1d"
metafile = true
