hash-format = "sha256"

[[files]]
file = "mods/animatium.pw.toml"
hash = "feede87454faf3e2b9bd2b207049d40b5d7b2a6c05b5e4978ec849328e6118e8"
metafile = true

[[files]]
file = "mods/audio-engine-tweaks.pw.toml"
hash = "82ce4ec3b926e8e4b9595d18e012e323c8e93058681088f49c8be5385e1c899d"
metafile = true

[[files]]
file = "mods/auto-gg.pw.toml"
hash = "5332f63ae6190e5abc7e33e09273ee34681ef18c28468de38c33fa6d8c2b470f"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "db0a9c4d44df3cc8a6f58dc233714a48a07edebe8b10fe9dfb7ed465e78127c7"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "a3b697198bf7d5c1323cffbc1018da984ae90b49778366a276dae9105f65ae3f"
metafile = true

[[files]]
file = "mods/betternightvision.pw.toml"
hash = "396f85cdfa6a7adb20837522efd40d5ca98386e997865d3e260b8d4c531693ea"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "7e1a4b2596c5d9b228726e1915033197d478b9d23d3a102d0acc4913d843172d"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "1f8ad7caf8ced5b688d9b1a6ab5174b1424788d2796a0f23b974b82e0c2b90f4"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "34fe00a0f5a3b3cd0f23df22adb64ad04c9decf41ae831bdba0ddb819d34dd7f"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "43d7dde1a382942adbeb4cd0eee6d91b494e393281f46db1ba56a80ef09a9cb5"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "4aa7f93edde1b5af8d6c5070916345ec66e2a6b107b21a4f1ce661b6b1111004"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "208c801e334a46912969bb47b0e21cc503e8a8fc75aa7d0aea85b9d32d7207ae"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "98e963bf5542d3bfec0eda3ec7b013b490b100a6098cd197dd24e6b0474179f0"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "16136396d0a0189c467994500f18f0c03953267593742d7df0a74eaaa07e9b2c"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "26bdfbdafb146c2a20aef65ca66a11c18fc936b6f7511bc23e75ca5b7ff8cfab"
metafile = true

[[files]]
file = "mods/island-utils.pw.toml"
hash = "12a016506ea8bfe9f1b01c255bf404a1775ca44e78256227e63b462c9ee97398"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "90233fb3e27362a245f6a7e9cbc7c03cb674f63b20af66951e3900a1f92bc394"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "efc92f6052675aabc048edaf10d088d59be43baadb38fbc602db39f540de3e02"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "068d940e40b9fe69e3e4de4438fae6f880b97c560a8d572882fd6d8e6f30f2d7"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "55d8a860d7cb567aa9d3e2011478a0233e9bd811070268b2fb90be4d84130dde"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "5881838144ba872521c23a672cafa42ea34fa3657e4282e9c6ecad0a3f1a1061"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "7f26f38d546a9fe1ae2a4b54f9a590cc82fe7190c2e6d9d06d5561bbf58b76af"
metafile = true

[[files]]
file = "mods/simple-block-overlay.pw.toml"
hash = "6988bc5582dafd56359c0a91966c5f1c5ce5bfd177de8826085ac147147599d3"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "8344ec411807b99f26dd6edd4aceea80275307e10ab01c23291f76d31cc4df35"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "32f8c57728d65b1a1ccddf0e10650e998266222585d68556407997fa28893fd3"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "dae0ad3e8ea16cbd080b72ec7ba5021b4a4754ee19b72f28b1898b1a49807b4e"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "582dd5cb00f2bfb46dfdd9db52d74a50f06676edc2829ff2c87bab5504b76605"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "c336639b7c1d51e0622465a31cb3f7affbb3cf05827fb89564fc4404fd84c012"
metafile = true

[[files]]
file = "mods/toggle-toggle-sprint.pw.toml"
hash = "7ac70dab23c1380e571edde0ac53ee9bf4560a80011e8f657db899ee987d2eaa"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1eb89ac2f78826052a7096368ee166836356939e1a139788c2d828f0b44a8371"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "2d87f42fb095a4c8dfd26847693eb43c2cb3added26e3b811ae5ddc09c830b4d"
metafile = true
