hash-format = "sha256"

[[files]]
file = "mods/animatium.pw.toml"
hash = "1b015241f9cf8d800b3261107e05862ae4487edb552538d0ebd4449b8e93dbc0"
metafile = true

[[files]]
file = "mods/audio-engine-tweaks.pw.toml"
hash = "54084808a66fae7c584fb4dc91a30d008fcbe3eedb3c0c52b35fee20b5069c27"
metafile = true

[[files]]
file = "mods/auto-gg.pw.toml"
hash = "0cac9b702be52d37070ee74127b8fe710544438adc0089087a4bd6a83edfd330"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "45acfbdf4b9331f7b5feba5663ece49e4b44ad472c0237d394d4418800fd556b"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "76b38089757f5d0429553a8730eedd7d8957f58ed124eade57c5042d9dbfa35a"
metafile = true

[[files]]
file = "mods/betternightvision.pw.toml"
hash = "a80e53a334ee3bd4c2ac4f06cf156a7843c91953e3724d7b0a64484010c68c1d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "76b6fda698cdd336a97069ad637d51a1687cad4f9e3fa393dca7464531320280"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "7987ea5dd452c99e88ba1ac9960393e3e3d4efd24abc58068c7411218a2a0084"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "6440cf4e68e958b086f49167bdce48083fef44848b2c4e6a61bbfd90ff7685eb"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "4c8ab1c27c20311bf90ccae90152c9a976751e9c26e89766b16a927f03249fa4"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "725d2b436f2d7214f705e8ff50b531357a2b502537c9bb054c199866d72f379c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "acc4a0b994139067300b21cc97a6f602da20b7008433c7f24d04b70ba44ec68c"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "4c1e84bb95c1b6955ed51373e41ab9b58a89bbdac3119c0b0fdd04edbb1ffd6d"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "2b621f20cbaf557486efdab667c2a6f899f4587d65db8ca6fe6c626d607be1a1"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "4d1a1125df7d7074edaa58a74a2e33fdda8daa197e9430e3566f434f409a607b"
metafile = true

[[files]]
file = "mods/island-utils.pw.toml"
hash = "9647e1806af82ad7fd4b9a23f648e4ec0e571fb7bfb417a350f091744b5d1936"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "3ad52e10e4e233b0c02b72f8db9ac46b3e023f052fb2b421c820e98a36fcaba4"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "485bf4fb694d45433b991e1954ca365cc25955d4090e4b7cee10d670830e7a2e"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "23e10be16a92569ea2d5295ae1c2a5208fcde8a89ef6cf42f01e458a62e74bd6"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "87237febecc1221a02828fe81d9aa2c265989f2cc3a5647ffbe1d3990b77c2c8"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "b8f3e4e7aeef1cf6390de735462abab11d1711938819a378ccb4f4fc22d0db4b"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "9ccfaef481c5afff672cb25e9434dc130d5f509c537f82abbc64e61bd0db57d1"
metafile = true

[[files]]
file = "mods/simple-block-overlay.pw.toml"
hash = "04a57b99a0d5b32eed72e2cddcebcc51e7f90d1ecc5e9f67087dea7eca41cbab"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "5b6fa8df2b8c66cb9e857a4b88bc4a15494a6a4d2769f45bd7b8281bdebbca5c"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "59eff3032920e6a9dfbdc88615eeec118ea3e1cb3926982f00e3f23832f8c9aa"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "9d8d27ec90b2c94f758ade5e469a954686f71441045dc6c91392f4d8d2c8071d"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "f2908d9033570d993a21f671304f08edb7696d65260b58e2b55d0c943f9b172c"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "90cea876b3016cd98db81ccf5de0b3c30b0f319588bc23307532a1b43e5390b3"
metafile = true

[[files]]
file = "mods/toggle-toggle-sprint.pw.toml"
hash = "ba7c986d1fdd9b3be52fb117f160aca629a05feb132e1bccbb7c5bc0c4775929"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "c056d4d548afba28d6d3b6899dca94119d36b556dc72c15853f41830ba983639"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "0c908e5acd7800589fa863d7240e5916053b82a44b0440874d3b1c550848fe42"
metafile = true
