hash-format = "sha256"

[[files]]
file = "mods/animatium.pw.toml"
hash = "1b015241f9cf8d800b3261107e05862ae4487edb552538d0ebd4449b8e93dbc0"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "f13f5c620cbd03e30a1f974b69f18f1e4ae7f6e2427b31c3eba822bfd1f9f0ef"
metafile = true

[[files]]
file = "mods/audio-engine-tweaks.pw.toml"
hash = "54084808a66fae7c584fb4dc91a30d008fcbe3eedb3c0c52b35fee20b5069c27"
metafile = true

[[files]]
file = "mods/auto-gg.pw.toml"
hash = "0cac9b702be52d37070ee74127b8fe710544438adc0089087a4bd6a83edfd330"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "45acfbdf4b9331f7b5feba5663ece49e4b44ad472c0237d394d4418800fd556b"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "76b38089757f5d0429553a8730eedd7d8957f58ed124eade57c5042d9dbfa35a"
metafile = true

[[files]]
file = "mods/betternightvision.pw.toml"
hash = "a80e53a334ee3bd4c2ac4f06cf156a7843c91953e3724d7b0a64484010c68c1d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "76b6fda698cdd336a97069ad637d51a1687cad4f9e3fa393dca7464531320280"
metafile = true

[[files]]
file = "mods/commandkeys.pw.toml"
hash = "968f1961472a5b770c357e3265f4eb3e9794213bbce1df11528762ca447178e7"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "1f589a6b0e98571664445901a56e602db68229d0ceba1f6bd9c2184c52ea1552"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "77ae21ed913af83ad741b7c54d3d6a9201cbc891dd6d2e0741d77c21f3ae0b7f"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "11e043bf815b74a2cf1ca826e550e6e9aa10aea4830f853e49760a299df4f752"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "436fece36e8837e8922762b74763f5600d0190d36c5f7974b02cc06a78a95c7b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "44a1e5fe868dec8804451d967789ede66adc5491417bef88bb9108ec7a8e1a13"
metafile = true

[[files]]
file = "mods/frozenlib.pw.toml"
hash = "204b1a59461e100cab310c9287e571a4765ed65fe1c6a0c2adf40a008ae4bd9c"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "2b621f20cbaf557486efdab667c2a6f899f4587d65db8ca6fe6c626d607be1a1"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "4d1a1125df7d7074edaa58a74a2e33fdda8daa197e9430e3566f434f409a607b"
metafile = true

[[files]]
file = "mods/island-utils.pw.toml"
hash = "9647e1806af82ad7fd4b9a23f648e4ec0e571fb7bfb417a350f091744b5d1936"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "3ad52e10e4e233b0c02b72f8db9ac46b3e023f052fb2b421c820e98a36fcaba4"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "485bf4fb694d45433b991e1954ca365cc25955d4090e4b7cee10d670830e7a2e"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "23e10be16a92569ea2d5295ae1c2a5208fcde8a89ef6cf42f01e458a62e74bd6"
metafile = true

[[files]]
file = "mods/noxesium.pw.toml"
hash = "87237febecc1221a02828fe81d9aa2c265989f2cc3a5647ffbe1d3990b77c2c8"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "b8f3e4e7aeef1cf6390de735462abab11d1711938819a378ccb4f4fc22d0db4b"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "9ccfaef481c5afff672cb25e9434dc130d5f509c537f82abbc64e61bd0db57d1"
metafile = true

[[files]]
file = "mods/simple-block-overlay.pw.toml"
hash = "04a57b99a0d5b32eed72e2cddcebcc51e7f90d1ecc5e9f67087dea7eca41cbab"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "508dbda0b7b04dcb8062bf845a9abe04d65f9991033ad380f5690ec7b1124618"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "59eff3032920e6a9dfbdc88615eeec118ea3e1cb3926982f00e3f23832f8c9aa"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "9d8d27ec90b2c94f758ade5e469a954686f71441045dc6c91392f4d8d2c8071d"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "f2908d9033570d993a21f671304f08edb7696d65260b58e2b55d0c943f9b172c"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "90cea876b3016cd98db81ccf5de0b3c30b0f319588bc23307532a1b43e5390b3"
metafile = true

[[files]]
file = "mods/toggle-toggle-sprint.pw.toml"
hash = "ba7c986d1fdd9b3be52fb117f160aca629a05feb132e1bccbb7c5bc0c4775929"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "46987b23d1c32199c3bb4db30ceca4a5260917a12c383e712a23f0736716a86f"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "0c908e5acd7800589fa863d7240e5916053b82a44b0440874d3b1c550848fe42"
metafile = true
