name = "OneClient 1.21.8 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.8-fabric"
update-url = "oneclient/generated/utility-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88dfa4989d052604c4a4c5d06bebfacb9b1db4fcf8e332f2a390c72f30ecb38b"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
