name = "OneClient 1.21.8 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.8-fabric"
update-url = "oneclient/generated/utility-1.21.8-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14a1c9d9937e069327c15c8855c1a43cd9d517df470f4b0773a920ac1b8be575"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = []
