name: "Generate Bundles"
on:
  workflow_dispatch:

jobs:
  GenerateBundles:
    name: generate Bundles
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Allow running the script
        run: chmod +x ./oneclient/generate-bundles.sh

      - name: Generate Bundles
        run: ./oneclient/generate-bundles.sh

      - name: Commit and push the generated bundles
        run: |
          git config --global user.name "Bundle Updater[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(generate-bundles)" || echo "No changes to commit"
          git push origin main
