name: 'Update Bundles'
on:
  workflow_dispatch:

jobs:
  UpdateBundles:
    name: Update Bundles
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Update Bundles
        run: ./oneclient/update-bundles.sh

      - name: Commit and push the updated bundles
        run: |
          git config --global user.name "Bundle Updater[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(update-bundles)" || echo "No changes to commit"
          git push origin main